<div class="unit">
	<div class="container">
	<div class="unit horizontal-center layout on-2 columns">
		<div class="fixed column" style="width:640px;padding-right:20px;">
			<?=$this->action('pencaharian','browser','hold'); ?>
			<div style="padding-top:15px;"></div>
			<?php 
				if ($this->node) { 
					echo str_replace('Root','',$this->action('view-folder-navigation', 'widgets_folder', 'hold', array('node' => $this->node)));
				} 
				elseif ($this->nprt) { 
					echo str_replace('Root','',$this->action('view-folder-navigation-peraturan', 'widgets_folder', 'hold', array('nprt' => $this->nprt)));
				} 
				elseif ($this->npts) {
					echo str_replace('Root','',$this->action('view-folder-navigation-putusan', 'widgets_folder', 'hold', array('npts' => $this->npts)));
				} 
			?>
			<div style="padding-top:15px;"></div>
			<?php 
				if ($this->nprt) {
					echo $this->action('viewer', 'widgets_catalog', 'hold', array('guid' => $this->catalogGuid,'nprt' => $this->nprt)); 
				} 
				elseif ($this->npts) {
					echo $this->action('viewer', 'widgets_catalog', 'hold', array('guid' => $this->catalogGuid,'npts' => $this->npts)); 
				} 
				else {
					echo $this->action('viewer', 'widgets_catalog', 'hold', array('guid' => $this->catalogGuid,'node' => $this->node)); 
				}
			?>
			<div class="bersih"></div>
			<div style="padding-top:15px;"></div>
			<?=$this->action('document', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid)); ?>
			<div class="bersih"></div>
			<div style="padding-top:15px;"></div>
			<?=$this->action('view-folder', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid)); ?>
			<div style="padding-top:15px;"></div>
			<?php 
				if ($this->nprt) {
					echo $this->action('view-dasar-hukum', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'nprt' => $this->nprt)); 
				} 
				elseif ($this->npts) {
					echo $this->action('view-dasar-hukum', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'npts' => $this->npts)); 
				} 
				else {
					echo $this->action('view-dasar-hukum', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'node' => $this->node)); 
				}
			?>
			<div style="padding-top:15px;"></div>
			<?php 
				if ($this->nprt) {
					echo $this->action('peraturan-pelaksana', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'nprt' => $this->nprt)); 
				} 
				elseif ($this->npts) {
					echo $this->action('peraturan-pelaksana', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'npts' => $this->npts)); 
				} 
				else {
					echo $this->action('peraturan-pelaksana', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'node' => $this->node)); 
				}
			?>
			<div style="padding-top:15px;"></div>
			<?php 
				if ($this->nprt) {
					echo $this->action('view-history', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'nprt' => $this->nprt)); 
				} 
				elseif ($this->npts) {
					echo $this->action('view-history', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'npts' => $this->npts)); 
				} 
				else {
					echo $this->action('view-history', 'widgets_relation', 'hold', array('guid' => $this->catalogGuid,'node' => $this->node)); 
				}
			?>
			
			<?=$this->action('other', 'widgets_relation', 'hold', array('parent' => $this->catalogGuid)); ?>
		</div>
		<div class="fixed column" style="width:300px;">
			<?=$this->action('kanan','widgets_sidebar','hol-site'); ?>
		</div>
	</div>
 	</div>
</div>