<div class="unit">
	<div class="container">
	<div class="unit horizontal-center layout on-2 columns">
		<div class="fixed column" style="width:640px;padding-right:20px;">
			<?=$this->action('pencaharian','browser','hold'); ?>
			<div style="padding-top:15px;"></div>
			<?=$this->action('view-result', 'widgets_search', 'hold', array('query' => $this->query)); ?>
		</div>
		<div class="fixed column" style="width:300px;">
			<?=$this->action('kanan','widgets_sidebar','hol-site'); ?>
		</div>
	</div>
 	</div>
</div>