<div id="loading-mask" style="width:100%;height:100%;position:absolute;z-index:20000;left:0;top:0;">&#160;</div>
<div id="loading" class="x-box-blue" style="width:360px">
	<div class="x-box-tl">
		<div class="x-box-tr">
			<div class="x-box-tc"></div>
		</div>
	</div>
	<div class="x-box-ml">
		<div class="x-box-mr">
			<div class="x-box-mc">
			<table>
			<tr>
				<td rowspan=2><img alt="hukumonline" src="<?=$this->baseUrl;?>/resources/images/frontpage.png" align="middle"/></td>
				<td colspan=2>
					<span style="font-weight: bold; color:#17385b">CMS Hukumonline</span>		
				</td>
			</tr>
			<tr>
				<td>
					<div class="loading-indicator">
					<table>
					<tr>
						<td>
							<img alt="loading" src="<?=$this->baseUrl;?>/js/extjs/resources/images/default/shared/large-loading.gif" style="width:32px;height:32px;vertical-align:middle" />			
						</td>
						<td>
							<span id="loading-msg" style="text-align:left;">Loading styles and images...</span>			
						</td>
					</tr>
					</table>
					</div>						
				</td>
			</tr>
			</table>
			</div>
		</div>
	</div>
	<div class="x-box-bl">
		<div class="x-box-br">
			<div class="x-box-bc"></div>
		</div>
	</div>		
</div>

<script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Loading Core API...';</script>
<script type="text/javascript" src="<?=$this->baseUrl;?>/js/extjs/adapter/ext/ext-base.js"></script>
<script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Loading UI Components...';</script>
<script type="text/javascript" src="<?=$this->baseUrl;?>/js/extjs/ext-all.js"></script>
<script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Initializing...';</script>
<script type="text/javascript" src="<?=$this->baseUrl;?>/js/extjs/plugin/miframe/miframe-min.js"></script>
<script type="text/javascript">document.getElementById('loading-msg').innerHTML = 'Finalizing...';</script>
<script src="<?=$this->baseUrl;?>/js/extjs/examples/shared/examples.js" type="text/javascript" charset="utf-8"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/plugin/theme/Ext.ux.ThemeCombo.js" type="text/javascript" charset="utf-8"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/layout/admin.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/layout/admin-min-function.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/plugin/BI.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/plugin/grid/PagingToolbar.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/plugin/grid/Ext.ux.grid.Search.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/plugin/grid/RowExpander.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/plugin/tab/TabCloseMenu.js" type="text/javascript"></script>
<!--<script src="<?=$this->baseUrl;?>/js/extjs/plugin/upload/FileUploadField.js" type="text/javascript"></script>-->
<script src="<?=$this->baseUrl;?>/js/extjs/plugin/combo/Ext.ux.form.LovCombo.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/extjs/plugin/message/MessageWindow.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/jquery/jquery-1.2.3.pack.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/jquery/form/jquery.form.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/jquery/form/jquery.delegate.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/jquery/form/jquery.validate.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/jquery/form/jquery.maskedinput.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/jquery/form/jquery.highlightFade.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/jquery/form/jquery.pstrength.js" type="text/javascript"></script>
<script src="<?=$this->baseUrl;?>/js/jquery/upload/jquery.MultiFile.min.js" type="text/javascript"></script>
<!--<script type='text/javascript' src='http://getfirebug.com/releases/lite/1.2/firebug-lite-compressed.js'></script>-->

<div id="datenow" class="ytb-text">Date : <?=strftime("%A, %d %B %Y",strtotime(date("Y-m-d"))); ?></div>

<div id="chdir" class="ytb-text">Location : <a style="font-size:10px; color:#666666; font-family:arial" href="javascript:void(0);" onclick="theDir='/'; chDir(theDir);">Root</a></div>

<div id="clock">
	<script type="text/javascript" src="<?=$this->baseUrl;?>/js/jquery/jclock/jquery.jclock.js"></script>
	<table>
		<tbody>
			<tr class="ytb-text">
				<td>Time : </td>
				<td><div class="jclock"></div></td>
			</tr>
		</tbody>
	</table>
	<script>
		$(function($) {
			$('.jclock').jclock();
		});
	</script>
	<div style="clear:both" ></div>
</div>

<div id="west"></div>
<div id="north"><div id="header-toolbar"></div></div>
<div id="center2"></div>
<div id="center1"><?=$this->action('panel','frontpanel','admin'); ?></div>
<div id="info" align="center">
	<div style="width: 198px; height: 500px;">
		<?php if (Zend_Auth::getInstance()->hasIdentity()) { ?>
		<div class="info" align="left">
			<div class="x-layout-panel-hd x-layout-panel-hd-text">
				Login Information
			</div>	
			<div class="body">
				<table>
					<tbody>
					<tr>
						<td>Welcome,</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
					</tr>
					<tr>
						<td>Username</td>
						<td>:</td>
						<td><?=Zend_Auth::getInstance()->getIdentity()->username ?><!--&nbsp;<a href="javascript:void(0);" onclick="ext_get('mod/servers/identity/account/profiles',700,500)"><img alt="profiles" src="<?=$this->baseUrl;?>/js/extjs/resources/images/default/silk/icons/user_edit.png" border="0" title="profile" style="vertical-align:middle" /></a>--></td>
					</tr>
					<tr>
						<td valign="top">Group</td>
						<td>:</td>
						<td><?=$this->group ?></td>
					</tr>
					<tr>
						<td>You last visited</td>
					</tr>
					<tr>
						<td colspan="4"><font color="Gray"><?=$this->lastlogin ?></font></td>					
					</tr>
					</tbody>
				</table>			
			</div>
		</div>
		<?php } ?>
	</div>
</div>
<div id="calendar" align="left">
		<div class="info" align="left">
			<div class="x-layout-panel-hd" style="cursor: pointer;" onclick="BI.infoView.toggle(this)">
			<div class="x-layout-panel-hd-text header x-layout-expand-north">
				Kalender
			</div>
			</div>
			<div style="display: block;">
				<div class="toolbar"></div>
				<div class="body">
					<table>
						<tbody class=" yui-skin-sam">
							<tr>
								<td>
								cal
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
</div>
<div id="legend" align="center">
	<div style="width: 198px; height: 500px;">
		<div class="info" align="left">
			<div class="x-layout-panel-hd" style="cursor: pointer;" onclick="BI.infoView.toggle(this)">
			<div class="x-layout-panel-hd-text header x-layout-expand-north">
				Legend 1
			</div>
			</div>
			<div style="display: block;">
				<div class="toolbar"></div>
				<div class="body">
					<table>
						<tbody>
							<tr>
								<td>P</td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Periode Pembayaran</td>
							</tr>
							<tr>
								<td>D</td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Jatuh Tempo dalam Hari</td>
							</tr>
							<tr>
								<td>E</td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Email Terkirim?</td>
							</tr>
							<tr>
								<td>EO</td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Email Peringatan Terkirim?</td>
							</tr>
							<tr>
								<td>S</td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Status</td>
							</tr>
							<tr>
								<td>C</td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Kontak Pengguna Korporasi</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="info" align="left">
			<div class="x-layout-panel-hd" style="cursor: pointer;" onclick="BI.infoView.toggle(this)">
			<div class="x-layout-panel-hd-text header x-layout-expand-north">
				Legend 2
			</div>
			</div>
			<div style="display: block;">
				<div class="toolbar"></div>
				<div class="body">
					<table width="100%">
						<tbody>
							<tr>
								<td bgcolor="#FFFF00" align="center">Masa berlangganan masih aktif</td>
							</tr>
							<tr>
								<td bgcolor="#FF0000" align="center"><font color="White">Masa trial sudah lewat</font></td>
							</tr>
							<tr>
								<td bgcolor="#C3FF8F" align="center"><font color="Red">Masa trial terakhir hari ini</font></td>
							</tr>
							<tr>
								<td bgcolor="#FFE5E5" align="center"><font color="Red">Masa berlangganan telah lewat</font></td>
							</tr>
							<tr>
								<td bgcolor="#6699CC" align="center"><font color="White">Pelanggan sudah bayar</font></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="info" align="left">
			<div class="x-layout-panel-hd" style="cursor: pointer;" onclick="BI.infoView.toggle(this)">
			<div class="x-layout-panel-hd-text header x-layout-expand-north">
				Legend 3
			</div>
			</div>
			<div style="display: block;">
				<div class="toolbar"></div>
				<div class="body">
					<table width="100%">
						<tbody>
							<tr>
								<td><img src="<?=$this->baseUrl;?>/js/extjs/resources/images/default/silk/icons/publish_y.png"></td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Published, but is Pending</td>
							</tr>
							<tr>
								<td><img src="<?=$this->baseUrl;?>/js/extjs/resources/images/default/silk/icons/publish_g.png"></td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Published and is Current</td>
							</tr>
							<tr>
								<td><img src="<?=$this->baseUrl;?>/js/extjs/resources/images/default/silk/icons/publish_r.png"></td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Published, but has Expired</td>
							</tr>
							<tr>
								<td><img src="<?=$this->baseUrl;?>/js/extjs/resources/images/default/silk/icons/publish_x.png"></td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Not Published</td>
							</tr>
							<tr>
								<td><img src="<?=$this->baseUrl;?>/js/extjs/resources/images/default/silk/icons/disabled.png"></td>
								<td>&nbsp;</td><td>&nbsp;</td>
								<td>:</td>
								<td>Archived</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

