<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<?=$this->render('index/_stylesheets1.phtml'); ?>
	<title>CMS Hukumonline</title>
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" />
</head>
<body>
<?=$this->render('index/_tpl1.phtml'); ?>
</body>
</html>