<? 
	// INITIALIZE JCART AFTER SESSION START
	$cart =& $_SESSION['jCart']; if(!is_object($cart)) $cart = new jCart();
	// INCLUDE CONFIG SO THIS SCRIPT HAS ACCESS USER FIELD NAMES
	include(ROOT_DIR.'/js/jcart/jcart-config.php');
	// INCLUDE DEFAULT VALUES SINCE WE NEED TO PASS THE VALUE OF THE UPDATE BUTTON BACK TO jcart.php IF UPDATING AN ITEM QTY
	// IF NO VALUE IS SET IN CONFIG, THERE HAS TO BE A DEFAULT VALUE SINCE SIMPLY CHECKING FOR THE VAR ITSELF FAILS
	include(ROOT_DIR.'/js/jcart/jcart-defaults.php');
?>

<script type="text/javascript" src="<?=ROOT_URL;?>/js/jcart/jcart-javascript.php"></script>

<form name="formTax" method="post" action="<?=ROOT_URL?>/store/confirmorder">
<div class="unit horizontal-center layout">
	<h2 style="font-weight:bold;">View Cart / Checkout</h2>
	<div class="bor"></div>
	<div style="padding-top:15px;"></div>
	<h3 style="color:#EE1625;font-weight:bold;font-size:1em;line-height:1;margin-bottom:1em;">Please verify your purchased items, total charges and proceed to secure payment.</h3>
	<h2>for previous orders you can view at &raquo; <a href="<?=ROOT_URL?>/store/payment/list">order history</a></h2>
	<div style="padding-top:15px;"></div>
	<table cellspacing="0" border="0" cellpadding="0" id="shopping-cart-table" class="data-table box-table shopping-cart">
	<thead>
	<tr>
		<th rowspan="1" colspan="2" class="a-left" style="padding-left:23px;border-left: 1px solid #cacaca;">Product Name</th>
		<th class="a-center" colspan="1">Price</th>
		<th rowspan="1" class="a-center">Quantity</th>
		<th class="a-center last" colspan="1">Total</th>
	</tr>
	</thead>
	<?
		$bpmCatalog = new Pandamp_Core_Hol_Catalog();
		
		$jcartId = $this->cart->items;
		$jcartProductInfo = $this->cart->iteminfo;

		$iCart = 0;
		$cartTotal = 0;
		$price = 0;
		for($iCart=0;$iCart<count($jcartId);$iCart++)
		{
			$modelCatalogAttribute = new Pandamp_Modules_Dms_Catalog_Model_CatalogAttribute();
			$price = $bpmCatalog->getPrice($jcartId[$iCart]);
			$cartTotal += $price;
			
			$sDir = ROOT_URL.'/uploads/images';
			$thumb = "";
			
			$modelRelatedItem = new Pandamp_Modules_Dms_Catalog_Model_RelatedItem();
			$rowsetRelatedItem = $modelRelatedItem->getDocumentById($jcartId[$iCart],'RELATED_IMAGE');
			$itemGuid = (isset($rowsetRelatedItem->itemGuid))? $rowsetRelatedItem->itemGuid : '';
			
			if (Pandamp_Lib_Formater::thumb_exists($sDir ."/". $itemGuid . ".jpg")) 	{ $thumb = $sDir ."/". $itemGuid . ".jpg"; 	}
			if (Pandamp_Lib_Formater::thumb_exists($sDir ."/". $itemGuid . ".gif")) 	{ $thumb = $sDir ."/". $itemGuid . ".gif"; 	}
			if (Pandamp_Lib_Formater::thumb_exists($sDir ."/". $itemGuid . ".png")) 	{ $thumb = $sDir ."/". $itemGuid . ".png"; 	}
			
			if ($thumb == "") { $thumb = "resources/images/nothumb.jpg"; }
			
			$screenshot = "<img src=\"".$thumb."\" width=\"125\" />";
			
	?>
	<tbody>
	<tr>
		<?php 	
		if ($thumb == "") { $screenshot = ""; } else { ?>
	    <td><a href=""><?=$screenshot; ?></a></td>
	    <?php } ?>
		<td class="attributes-col">
			<h4 class="title" style="margin-bottom:5px;"><a href=""><?echo $jcartProductInfo[$jcartId[$iCart]];?></a></h4>
			<span style="font-size:11px;"><a href="<?echo ROOT_URL;?>/store/cart/removeitem/id/<?echo $jcartId[$iCart];?>">remove</a></span>
		</td>
		<td class="a-right">
		<div class="cart-price">
		<span class="price">Rp. <?echo number_format($price,2);?></span> 
		</div>
		</td>
		<td class="a-center">1</td>
		<td class="a-right last">
		<div class="cart-price">
		<span class="price">Rp. <?echo number_format($price,2);?></span>
		</div>
		</td>
	</tr>
	
	<?	}?>
	</tbody>
	</table>
	<table style="border: 1px solid #cacaca; border-top: 0;width:90%;">
	<tr>
		<td style="padding: 0px 0px 0px 10px;" valign="top">
		<div class="shopping-cart-totals">
		<table cellspacing="0" id="shopping-cart-totals-table">
		<tbody>
		<tr>
			<td valign="middle" align="right" style="color: #444;text-transform: uppercase;" class="a-right" colspan="2">
			Subtotal
			</td>
			<td>:</td>
			<td class="a-right" width="20%">
			<span class="price">Rp. <?echo number_format($cartTotal,2);?></span>
			</td>
		</tr>
		</tbody>
		</table>
		</div>
		</td>
	</tr>
	</table>
	
	<div style="padding-top:15px;"></div>
	
	<h3 style="color:#EE1625;font-weight:bold;font-size:1em;line-height:1;margin-bottom:1em;">BILLING INFORMATION</h3>
</div>
<div class="unit horizontal-center layout on-2 columns">
	<div class="fixed column" style="width:330px;padding-right:20px;">
		Tax Number
		<br>
		<input name="taxNumber" value="<?=$this->userInfo->taxNumber?>">
		<br>
		Company Name
		<br>
		<input name="taxCompany" value="<?=$this->userInfo->taxCompany?>">
		<br>
		Address
		<br>
		<textarea name="taxAddress"><?=$this->userInfo->taxAddress?></textarea>
	</div>
	<div class="fixed column" style="width:300px;padding-right:10px;padding-left:5px;">
		City
		<br>
		<input name="taxCity" value="<?=$this->userInfo->taxCity?>">
		<br>
		Zip
		<br>
		<input name="taxZip" value="<?=$this->userInfo->taxZip?>">
		<br>
		Province
		<br>
		<input name="taxProvince" value="<?=$this->userInfo->taxProvince?>">
		<br>
		<label for="taxCountry">* Country</label>
		<?php echo $this->formSelectCountries('taxCountry', $this->userInfo->taxCountryId);?>
	</div>
</div>
<script type="text/javascript" language="javascript">
function setSubmitAction(newUrl)
{
      var frm = document.formTax;
      frm.action =newUrl;            
      frm.submit();
      return true;
}
</script>

<div class="unit horizontal-center layout">
	<div style="padding-top:15px;"></div>
	<div class="bor"></div>
	<div style="padding-top:15px;"></div>
	
	<h3 style="color:#EE1625;font-weight:bold;font-size:1em;line-height:1;margin-bottom:1em;">SELECT PAYMENT METHOD</h3><br>
	
	<select name="method" id="method" style="width:200px;">
		<option value="pilih">-- Pilih --</option>
		<option value="manual" >Bank Transfer</option>
		<option value="nsiapay" >NsiaPay</option>
		<option value="postpaid" >Postpaid</option>
	</select>
	
	<div style="padding-top:15px;"></div>
	<div class="bor"></div>
	<div style="padding-top:15px;"></div>
	
	<input type="submit" value="Confirm Order" />	
</div>
</form>