<? 
	// INITIALIZE JCART AFTER SESSION START
	$cart =& $_SESSION['jCart']; if(!is_object($cart)) $cart = new jCart();
	// INCLUDE CONFIG SO THIS SCRIPT HAS ACCESS USER FIELD NAMES
	include(ROOT_DIR.'/js/jcart/jcart-config.php');
	// INCLUDE DEFAULT VALUES SINCE WE NEED TO PASS THE VALUE OF THE UPDATE BUTTON BACK TO jcart.php IF UPDATING AN ITEM QTY
	// IF NO VALUE IS SET IN CONFIG, THERE HAS TO BE A DEFAULT VALUE SINCE SIMPLY CHECKING FOR THE VAR ITSELF FAILS
	include(ROOT_DIR.'/js/jcart/jcart-defaults.php');
?>

<script type="text/javascript" src="<?=ROOT_URL;?>/js/jcart/jcart-javascript.php"></script>

<div class="unit horizontal-center layout">
	<h2 style="font-weight:bold;">Confirm Your Order</h2>
	<div class="bor"></div>
	<div style="padding-top:15px;"></div>
	<h3 style="color:#EE1625;font-weight:bold;font-size:1em;line-height:1;margin-bottom:1em;">Please verify your purchased items, total charges and complete the order.</h3>
	<div style="padding-top:15px;"></div>
	
	<table>
	<tr>
		<td>Product Name</td>
		<td>Price</td>
		<td>Quantity</td>
		<td>Total</td>
	</tr>
	<?
		$bpmCatalog = new Pandamp_Core_Hol_Catalog();
		$jcartId = $this->cart['items'];

		$iCart = 0;
		$cartTotal = 0;
		$price = 0;
		for($iCart=0;$iCart<count($jcartId);$iCart++)
		{
			$modelCatalogAttribute = new Pandamp_Modules_Dms_Catalog_Model_CatalogAttribute();
			$price = $bpmCatalog->getPrice($jcartId[$iCart]['itemId']);
			$cartTotal += $price;
	?>

	<tr>
		<td>
			<strong><?echo $jcartId[$iCart]['item_name'];?></strong>
			<br>
			<?echo $modelCatalogAttribute->getCatalogAttributeValue($jcartId[$iCart]['itemId'],'fixedSubTitle');	?>
			<br>&nbsp;
		</td>
		<td>Rp. <?echo number_format($price,2);?></td>
		<td>1</td>
		<td>Rp. <?echo number_format($price,2);?></td>
	</tr>
	<?	}?>
	<tr>
		<td colspan="2"></td>
		<td>Sub Total</td>
		<td>Rp. <?echo number_format($cartTotal,2);?></td>
	</tr>
	<tr>
		<td colspan="2"></td>
		<td>Tax 10%</td>
		<td>Rp. <?echo number_format($this->cart['taxAmount'],2);?></td>
	</tr>
	<tr>
		<td colspan="2"></td>
		<td>Grand Total</td>
		<td>Rp. <?echo number_format($this->cart['grandTotal'],2);?></td>
	</tr>
	</table>
	
	<div style="padding-top:15px;"></div>
	<div class="bor"></div>
	<div style="padding-top:15px;"></div>
	
	<h3 style="color:#EE1625;font-weight:bold;font-size:1em;line-height:1;margin-bottom:1em;">BILLING INFORMATION</h3>
	
</div>
<div class="unit horizontal-center layout on-2 columns">
	<div class="fixed column" style="width:330px;padding-right:20px;">
		Tax Number
		<br>
		<?=($this->data['taxNumber'])?$this->data['taxNumber']:'-';?>
		<br>
		Company Name
		<br>
		<?=($this->data['taxCompany'])?$this->data['taxCompany']:'-';?>
		<br>
		Address
		<br>
		<?=($this->data['taxAddress'])?$this->data['taxAddress']:'-';?>
	</div>
	<div class="fixed column" style="width:300px;padding-right:10px;padding-left:5px;">
		City
		<br>
		<?=($this->data['taxCity'])?$this->data['taxCity']:'-';?>
		<br>
		Zip
		<br>
		<?=($this->data['taxZip'])?$this->data['taxZip']:'-';?>
		<br>
		Province
		<br>
		<?=($this->data['taxProvince'])?$this->data['taxProvince']:'-';?>
		<br>
		<strong>Country</strong>
		<br>
		<?=($this->data['taxCountry'])?$this->data['taxCountry']:'-';?>
	</div>
</div>
<div class="unit horizontal-center layout">
	<div style="padding-top:15px;"></div>
	<div class="bor"></div>
	<div style="padding-top:15px;"></div>
	
	<h3 style="color:#EE1625;font-weight:bold;font-size:1em;line-height:1;margin-bottom:1em;">PAYMENT METHOD: <?=$this->data['method'];?></h3>
	
	<form method="post" action="<?=ROOT_URL;?>/store/completeorder">
	<input type="hidden" name="taxNumber" value="<?=$this->data['taxNumber']; ?>">
	<input type="hidden"  name="taxCompany" value="<?=$this->data['taxCompany']; ?>">
	<input type="hidden"  name="taxAddress" value="<?=$this->data['taxAddress']; ?>">
	<input type="hidden"  name="taxCity" value="<?=$this->data['taxCity']; ?>">
	<input type="hidden"  name="taxZip" value="<?=$this->data['taxZip']; ?>">
	<input type="hidden"  name="taxProvince" value="<?=$this->data['taxProvince']; ?>">
	<input type="hidden"  name="taxCountry" value="<?=$this->data['taxCountry']; ?>">
	<input type="hidden"  name="paymentMethod" value="<?=($this->data['method']=='manual')?'bank':$this->data['method']; ?>">
	<input type="button" onclick="javascript:history.back();" value="cancel">&nbsp;&nbsp;<input type="submit" value="Complete Order">
	</form>

</div>