<div class="info">
	<div class="x-layout-panel-hd" style="cursor: pointer;" onclick="BI.infoView.toggle(this)">
		<div class="x-layout-panel-hd-text header x-layout-expand-north">Membership </div>
	</div>
	<div style="display: block;">
	<div class="toolbar"></div>
	<div class="body">
		<table>
		<tr>
			<td>Active</td>
			<td>:</td>
			<td><?=$this->active; ?></td>
		</tr>
		<tr>
			<td>InActive</td>
			<td>:</td>
			<td><?=$this->inactive; ?></td>
		</tr>
		</table>
	</div>
	</div>
</div>