<div style="width: 198px; height: 55px;">
	<div class="info">
		<div class="x-layout-panel-hd" style="cursor: pointer;" onclick="BI.infoView.toggle(this)">
			<div class="x-layout-panel-hd-text header x-layout-expand-north">Catalog Index</div>
		</div>
		<div style="display: block;">
			<div class="toolbar"></div>
			<div class="body">
			<table>
			<tr>
				<td><div id="catalog-index"><?=$this->valueText; ?></div></td>
			</tr>
			</table>
			</div>
		</div>
	</div>
</div>
