<div class="info">
	<div class="x-layout-panel-hd" style="cursor: pointer;" onclick="BI.infoView.toggle(this)">
		<div class="x-layout-panel-hd x-layout-panel-hd-text">Document Management</div>
	</div>
	<div style="display: block;">
	<div class="toolbar"></div>
	<div class="body">
		<table>
		<tr>
			<td>Total Catalog(s)</td>
			<td>:</td>
			<td><?=$this->totalCatalog; ?></td>
		</tr>
		<tr>
			<td>Total Document(s)</td>
			<td>:</td>
			<td><?=$this->totalDoc; ?></td>
		</tr>
		</table>		
	</div>
	</div>
</div>
