<div class="info">
	<div class="x-layout-panel-hd" style="cursor: pointer;" onclick="BI.infoView.toggle(this)">
		<div class="x-layout-panel-hd x-layout-panel-hd-text">Article</div>
	</div>
	<div style="display: block;">
	<div class="toolbar"></div>
	<div class="body">
		<table>
		<tr>
			<td><div id="catalog-index">Total Article : <?=$this->TotalArticle; ?></div></td>
		</tr>
		</table>		
	</div>
	</div>
</div>
