<table align="center">
<tr>
	<td>&nbsp;</td>
</tr>
<tr>
	<td valign="top"><?=$this->action('panel-article','frontpanel','admin'); ?><br><?=$this->action('panel-dms','frontpanel','admin'); ?></td>
	<td valign="top"><div style="width: 198px; height: 300px;"><?=$this->action('panel-membership','frontpanel','admin'); ?><?=$this->action('panel-clinic','frontpanel','admin'); ?></div></td>
	<td valign="top"><div id="comments"><?=$this->action('panel-comment','frontpanel','admin'); ?></div></td>
	<td valign="top"><?=$this->action('panel-index','frontpanel','admin'); ?></td>
</tr>
</table>
