<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>hukumonline.com Klinik : <?php echo $this->getCatalogAttribute($this->catalogGuid,'fixedCommentTitle'); ?></title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<?
	if($this->catalogGuid!="")
	{
	?>
	<meta property="og:title" content="<?php echo $this->getCatalogAttribute($this->catalogGuid,'fixedCommentTitle'); ?>" />
	<?
	}
	?>
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/jquery-1.2.3.pack.js"></script>
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/elastic.css" />
	<script src="<?=$this->baseUrl();?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/typography.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/calender.css" />
	<link rel="stylesheet" href="<?=$this->baseUrl(); ?>/js/jquery/paging/pagination.css" type="text/css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/js/jquery/tabs/jquery.tabs.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/js/jquery/tabs/jquery.tabs-ie.css" />
	<script src="<?=$this->baseUrl();?>/js/jquery/newsticker/jquery.newsticker.pack.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/paging/jquery.pagination.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/form/jquery.form.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/form/jquery.delegate.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/form/jquery.validate.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/tabs/jquery.tabs.pack.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/smooth.scroller.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/globe.js" type="text/javascript"></script>
	<script type="text/javascript">
	$(document).ready(function(){
		$guid = '<?=$this->catalogGuid; ?>';
		getRating($guid);
		function getRating(guid)
		{
			$.ajax({
				type:"GET",
				dataType:'json',
				url:"<?=$this->getRootUrl(); ?>/getrate",
				data:"guid="+guid,
				cache:false,
				async:false,
				success: function(result) {
					if (result.error == -1) {
						$('#ratelinks').remove();
						$("#current-rating-"+guid+"").css({ width: "" + result.data + "%" });
					}
					else
					{
						$("#current-rating-"+guid+"").css({ width: "" + result.data + "%" });
					}
				},
				error: function(result) {
					alert("some error occured, please try again later");
				}	
			});
		}
		// link handler
		$('#ratelinks li a').click(function(){
			$.ajax({
				type: "GET",
				dataType: 'json',
				url: "<?=$this->baseUrl(); ?>/rate",
				data: "rating="+$(this).text()+"&guid="+$guid,
				cache: false,
				async: false,
				success: function(result) {
					if (result.error == -1) {
						$("#ratelinks").remove();
						$('.votitaly-box').append(result.message);
					}
					else
					{
						// remove #ratelinks element to prevent another rate
						$("#ratelinks").remove();
						// get rating after click
						getRating($guid);
						// then update it
						$('.votitaly-box').empty();
						$('.votitaly-box').html(result.message);
					}
				},
				error: function(result) {
					alert("some error occured, please try again later");
				}
			});
		});
	});
	</script>
</head>
<body>
	<?=$this->render("header.phtml"); ?>
	<div style="padding-top: 5px"></div>
	<?=$this->layout()->content?>
	<?=$this->render("footer.phtml"); ?>
	<script type="text/javascript">
	$('#container-2').tabs();
	</script>
	
	<script type="text/javascript">
	
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	
	</script>
	
	<script type="text/javascript">
	
	try{
	
	var pageTracker = _gat._getTracker("UA-2695772-1");
	
	pageTracker._trackPageview();
	
	} catch(err) {}
	
	</script>	
	
</body>
</html>