<div class="td_peraturan1">
	<div class="judulnaik">
		<h1>Fokus</h1>
	</div>
	<div class="bor"></div>
	<div class=c-isi>
	<?php for($i=0; $i<$this->numberOfRows;$i++) { ?>	
		<h2><a href="<?=$this->getRootUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5]; ?>"><?=$this->data[$i][0]; ?></a></h2>
		<div class="author"><?=$this->data[$i][1]; ?></div>
		<p><?=Pandamp_Lib_Formater::string_limit_words($this->data[$i][2],30);?></p>
		<div class="bb"><img src="<?=$this->getRootUrl(); ?>/resources/images/comment.jpg" width="13" height="9" /><a href="<?=$this->getRootUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5]; ?>#comments"> <?=$this->data[$i][3]; ?> tanggapan </a> |<a href="<?=$this->getRootUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5];?>"> Selengkapnya </a> |<a href="<?=$this->getRootUrl(); ?>/warta/fokus"> Index</a></div>
	<?php } ?>		
	</div>
</div>