<div class="td_footer">
	<div id="footer" style="padding-left:5px;">
<?php if ($this->numberOfRows == 0) { ?>
<div style="font:11px verdana,arial,helvetica,sans-serif;font-weight:bold;line-height: 16px;color: #999999;">Tidak ada talk</div>
<?php } ?>

<?php 
$sDir = $this->getRemoteImageUrl();
for ($i=0; $i<$this->numberOfRows;$i++) { 
	
	$thumb = "";
	$guid = $this->data[$i][1];
	
	$modelRelatedItem = new Pandamp_Modules_Dms_Catalog_Model_RelatedItem();
	$rowsetRelatedItem = $modelRelatedItem->getDocumentById($guid,'RELATED_IMAGE');
	$itemGuid = (isset($rowsetRelatedItem->itemGuid))? $rowsetRelatedItem->itemGuid : '';
	
	$chkDir = $sDir."/".$guid."/".$itemGuid;
	if (@getimagesize($chkDir))
	{
		$pict = $sDir ."/". $guid ."/". $itemGuid;
	}
	else 
	{
		$pict = $sDir ."/". $itemGuid;
	}
	

	if (Pandamp_Lib_Formater::thumb_exists($pict . ".jpg")) 	{ $thumb = $pict . ".jpg"; 	}
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".gif")) 	{ $thumb = $pict . ".gif"; 	}
	if (Pandamp_Lib_Formater::thumb_exists($pict . ".png")) 	{ $thumb = $pict . ".png"; 	}

    $screenshot = "<img src=\"".$thumb."\" alt=\"".$this->data[$i][0]."\" width=\"60\" height=\"60\" />";

	?>
	<div class="ft-isi">
	<? if (!empty($thumb)) : ?>
    <div class="image"><?=$screenshot; ?></div>
    <? endif; ?>
	<h2><a href="<?=$this->getRootUrl(); ?>/berita/baca/<?=$this->data[$i][1]; ?>/<?=$this->data[$i][2]; ?>"><?=$this->data[$i][0]; ?></a></h2>    
	</div>
	<div class="bersih"></div>
<?php } ?>			
<div id="mline">
<a href="<?=$this->getRootUrl(); ?>/talks">&raquo; More</a>
</div>
	
</div>
</div>