<div class="td_peraturan4">
	<div class="judulnaik1">
		<h1>Tokoh</h1>
	</div>
	<div class="bor"></div>
	<div class="kotakisi">
		<?php for($i=0; $i<$this->numberOfRows;$i++) { ?>
		<h2><a href="<?=$this->getRootUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5]; ?>"><?=$this->data[$i][0]; ?></a></h2>
		<div class="author"><?=$this->data[$i][1]; ?></div>
		<p><?=Pandamp_Lib_Formater::string_limit_words($this->data[$i][2],10);?></p>
	    <div class="bb"><img src="resources/images/comment.jpg" width="13" height="9" /><a href="<?=$this->getRootUrl(); ?>/berita/baca/<?=$this->data[$i][4]; ?>/<?=$this->data[$i][5]; ?>#comments"> <?=$this->data[$i][3]; ?> tanggapan </a> |<a href="<?=$this->getRootUrl(); ?>/warta/tokoh"> Index </a></div>
		<?php } ?>
	</div>
</div>
