<!-- our error cc -->
<div class="cc">
<ol>
	<li></li>
</ol>
</div>
<form id="frmEditPassword" name="frmEditPassword" method="post" action="">
<p>Nama Sandi ini akan digunakan jika anda ingin mengakses ke Hukumonline.</p><br>
<table>
<tbody>
<tr>
	<td width="25%"><label for="opasswd" class="input required">Old password</label></td>
	<td><input name="opasswd" id="opasswd" type="password" value="" maxlength="20" /></td>
</tr>
<tr>
	<td><label for="newpasswd" class="input required">New password</label></td>
	<td><input name="newpasswd" id="newpasswd" type="password" class="password" value="" maxlength="20" /></td>
</tr>
<tr>
	<td><label for="rpasswd" class="input required">Retype password</label></td>
	<td><input name="rpasswd" id="rpasswd" type="password" value="" maxlength="20" /></td>
</tr>
</tbody>
</table>
<input type="hidden" name="guid" id="guid" value="<?=$this->row->guid;?>">
<p class="buttons"><input value="Ubah" type="submit"></p>

</form>
<script type="text/javascript">
$('.password').pstrength();
var cc = $('div.cc');
$('#frmEditPassword').validate({
	errorContainer: cc,
	errorLabelContainer: $("ol", cc),
	wrapper: 'li',
	meta: "validate",
	rules: {
		opasswd: "required",
		newpasswd: "required",
		rpasswd: {
			required: true,
			equalTo: "#newpasswd"
		}
	},
	messages: {
		opasswd: "Enter old password",
		newpasswd: "Enter new password",
		rpasswd: {
			required: "Please provide a password",
			equalTo: "Please enter the same password as above"
		}
	}
});

var message = "<?echo $this->message;?>";
if(message!="")
{
	alert (message);
}
</script>