<script type="text/javascript">
// Add the additional 'advanced' VTypes
Ext.apply(Ext.form.VTypes, {
    daterange : function(val, field) {
        var date = field.parseDate(val);

        if(!date){
            return;
        }
        if (field.startDateField && (!this.dateRangeMax || (date.getTime() != this.dateRangeMax.getTime()))) {
            var start = Ext.getCmp(field.startDateField);
            start.setMaxValue(date);
            start.validate();
            this.dateRangeMax = date;
        } 
        else if (field.endDateField && (!this.dateRangeMin || (date.getTime() != this.dateRangeMin.getTime()))) {
            var end = Ext.getCmp(field.endDateField);
            end.setMinValue(date);
            end.validate();
            this.dateRangeMin = date;
        }
        /*
         * Always return true since we're only using this vtype to set the
         * min/max allowed values (these are tested for after the vtype test)
         */
        return true;
    }
});

var dr = new Ext.FormPanel({
	labelWidth:125,
	frame:true,
	title:'Date Range',
	bodyStyle:'padding:5px 5px 0',
	width:350,
	defaults:{ width:175 },
	defaultType:'datefield',
	items:[{
		fieldLabel:'Start Date',
		name:'startdt',
		id:'startdt',
		vtype:'daterange',
		endDateField:'enddt',
		format:'Y-m-d'
	},{
		fieldLabel:'End Date',
		name:'enddt',
		id:'enddt',
		vtype:'daterange',
		startDateField:'startdt',
		format:'Y-m-d'
	}, 
	new Ext.Button({
		text:'Generate',
		handler:function(btn,e){
			var startdt = Ext.get('startdt').getValue();
			var enddt = Ext.get('enddt').getValue();
			var rpt = '<?php echo $this->report; ?>';
			Ext.Ajax.on('beforerequest',function(){
				Ext.MessageBox.wait('Process ...');
			});
			Ext.Ajax.request({
				url:'./services/catalog/fetch-catalogs-in-folder',
				params:{
					startdt:startdt,
					enddt:enddt,
					report:rpt
				},
				callback: function(options, success, response ) {
					if( success ) {
						var result = Ext.decode( response.responseText );
//						if (result.success == true) {
							store.baseParams = {startdt:startdt,enddt:enddt,report:rpt};
							store.load({params:{start:0, limit:25, startdt:startdt,enddt:enddt,report:rpt }});
							dialog.destroy();
							dialog.hide();
//						}
					}
				}
			});
			Ext.Ajax.on('requestcomplete',function(){
				Ext.MessageBox.hide();
			});
		}
	}
	)
	]
});

Ext.getCmp('dialog_window1').add(dr);
Ext.getCmp('dialog_window1').doLayout();

</script>