<?php if (count($this->rowsetRelatedItem) > 0) { ?>
<fieldset>
	<legend>Dokumen</legend>
	<ul id="docline">
	<?php foreach ($this->rowsetRelatedItem as $row){?>
	<li>
		<?=$this->GetCatalogDocType($row->itemGuid); ?>&nbsp;
		<a href="<?=$this->baseUrl();?>/pusatdata/download/<?=$row->itemGuid;?>/parent/<?=$row->relatedGuid;?>"><?=$this->getCatalogTitle($row->itemGuid); ?></a>&nbsp;
		<?=$this->GetCatalogDocSize($row->itemGuid); ?>
	</li>
	<?php } ?>
	</ul>
</fieldset>
<?php } ?> 