<style type="text/css">
.messagebox { position:absolute; width:100px; margin-left:30px; border:1px solid #c93; background:#ffc; padding:3px; }
.messageboxok { position:absolute; width:auto; margin-left:30px; border:1px solid #349534; background:#C9FFCA; padding:3px; font-weight:bold; color:#008000; }
.messageboxerror { position:absolute; width:auto; margin-left:30px; border:1px solid #CC0000; background:#F7CBCA; padding:3px; font-weight:bold; color:#CC0000; }
form.rfgform label.error, label.error {
	/* remove the next line when you have trouble in IE6 with labels in list */
	display: none;
	color: red;
}
div.error { display: none; }
input.error { border: 1px dotted red; }
#settingenglish label.error { margin-left: 10px; width: auto; display: inline; }
</style>
<div style="width:auto;">
    <div class="x-box-tl"><div class="x-box-tr"><div class="x-box-tc"></div></div></div>
    <div class="x-box-ml"><div class="x-box-mr"><div class="x-box-mc">
    	<h3 style="margin-bottom:5px;"><img border="0" height="14" width="14" src="./js/extjs/resources/images/default/silk/icons/anchor.png">&nbsp;Setting</h3><br>
    	<form id="settingenglish">
    		<table>
    		<tr>
    			<td><label for="status">Offline</label></td>
    			<td>
    			<?php 
    			if ($this->rowset->status == 1)
    				$isChecked = 'checked';
    			else 
    				$isChecked = '';
    			?>
    			<input name="status" type="checkbox" value="1" <?=$isChecked; ?>>
    			</td>
    		</tr>
    		</table>
    		<input type="hidden" name="id" id="id" value="1">
    		<p class="buttons"><input value="Simpan" type="submit"><span id="msgbox" style="display:none"></span></p>
    	</form><div id="settingSpinner" style="color:red; display:none;"><img src="<?=$this->baseUrl();?>/resources/images/wait-trans.gif" border="0"> Sending Request</div>
    </div></div></div>
    <div class="x-box-bl"><div class="x-box-br"><div class="x-box-bc"></div></div></div>
</div>
<script type="text/javascript">
$.validator.setDefaults({
	submitHandler: function() {
		var options = {
			type: 'post',
			dataType: 'json',
			url: './admin/setting_manager/process',
			beforeSubmit: prepareData,
			success: function(response) {
				if (response.success == true)
				{
				  	$("#msgbox").fadeTo(200,0.1,function() 
					{ 
						$(this).html('Update successfully').addClass('messageboxok').fadeTo(900,1,
						function(){
							dialog.destroy();
							dialog.hide();
						});
					});
				}
				else
				{
				  	$("#msgbox").fadeTo(200,0.1,function()
					{ 
					  	$(this).html(response.error.message).addClass('messageboxerror').fadeTo(900,1);
					});		
				}
				$('#settingSpinner').hide();
			}
		};
		$('#settingenglish').ajaxForm(options);
	}
});

// validate registration_form on keyup and submit
$('#settingenglish').validate({
	rules : {
	},
	messages : {
	}
});

function prepareData() 
{ 
   	$('#settingSpinner').show();
   	$("#msgbox").removeClass().addClass('messagebox').text('Saving ...').fadeIn(1000);
} 
</script>