<?php
/**
 * @package holemp
 * @copyright 2009-2010 www.hukumonline.com
 * @author Nihki Prihadi <nihki@hukumonline.com>
 *
 * $error: error.phtml 2009-07-11 11:03
 */
?>

<!DOCTYPE htmlPUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>
<head>
    <title>Error Management</title>


</head>

<body>
 <h1>Error Management</h1>

 <strong>code: </strong><?php echo $this->error->code; ?><br />
 <strong>file: </strong><?php echo $this->error->file; ?><br />
 <strong>line: </strong><?php echo $this->error->line; ?><br />
 <strong>message: </strong><?php echo $this->error->message; ?><br />
 <strong>type: </strong><?php echo $this->error->type; ?><br />

</body>
</html>