<?php if ($this->aData['totalCount'] != 0) { ?>
<table>
<tr>
	<td style="color: #003366;font-size: 12px;">Jumlah data yang ditemukan dalam kategori ini : <?=$this->aData['totalCountRows'];?> (<?=$this->time; ?>)</td>
</tr>
</table>
<br><div id='catalogContent'></div><br>
<table>
	<tr>
		<td width=25%>&nbsp;</td>
		<td align="center"><div id='catalogPagination' class="pagination"></div></td>
	</tr>
</table>


<script>

$(document).ready(function(){
	
	var isFirstTime = 1;
	
	var myPageIndex = 0;
	
	$("#catalogPagination").pagination(<?=$this->aData['totalCount'];?>, 
	{items_per_page:<?=$this->aData['limit'];?>, callback:handlePaginationClick, next_text:'Berikutnya',prev_text:'Sebelumnya'}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		myPageIndex = new_page_index;
		myStart = (<?=$this->aData['limit'];?> * myPageIndex);
		
		if(true)
		{
			if($('#tblCatalogPager-'+myPageIndex).length==0)
			{
				$.getJSON('<?=$this->getRootUrl();?>/warta/indexcom/<?=$this->aData['folderGuid'];?>/'+myStart+'/<?=$this->aData['limit'];?>', '', catalogResult);
			}
			else
				showCatalogContent();
		}
		return false;
	}
	
	function catalogResult(res)
	{
		size = res.indexcom.length;
		var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<table class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
		for(i=0;i<size;i++)
		{
			tblRow += 
				
				"<tr valign=top>"
				+"<td width=25 class='jam'>["+res.indexcom[i].createdDate+"]</td>"
				+"<td><div id=peraturan><a class=linkhref href='<?=$this->getRootUrl();?>/berita/baca/"+res.indexcom[i].guid+"/"+res.indexcom[i].shortTitle+"'>"+res.indexcom[i].title+"</a>"
				+"</td>"
				+"</tr>";
				
		}
		tblRow += "</table>";
		$(tblRow).appendTo("#catalogContent");
		showCatalogContent();
	}
	function showCatalogContent()
	{
		$('.tblCatalogPager').hide();
		$('#tblCatalogPager-'+myPageIndex).show();
		if(!isFirstTime)
			Scroller.scroll();
		isFirstTime = 0;
	}
	
	
});



</script>
<?php } ?>