<div style="margin-left:50px;">
        <ul id="menu">
         	<a href="<?=$this->getRootUrl();?>/talks"><img style="float:left;" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/menu_left.png"/></a>
            <li><a href="#">Login</a>
            </li>
            <li><a href="#">Help</a>
                <ul id="help">
                    <li>
                        <img class="corner_inset_left" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/corner_inset_left.png"/>
                        <a href="#">General help</a>
                        <img class="corner_inset_right" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/corner_inset_right.png"/>
                    </li>
                    <li><a href="#">Posts</a></li>
                    <li><a href="#">Pages</a></li>
                    <li class="last">
                        <img class="corner_left" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/corner_left.png"/>
                        <img class="middle" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/dot.gif"/>
                        <img class="corner_right" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/corner_right.png"/>
                    </li>
                </ul>
            </li>
            <li class="searchContainer">
                <div>
                <input type="text" id="searchField" />
                <img src="<?=$this->baseUrl();?>/resources/images/vimeo/magnifier.png" alt="Search" onclick="alert('You clicked on search button')" /></div>
                <ul id="search">
                    <li>
                        <img class="corner_inset_left" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/corner_inset_left.png"/>
                        <input id="cbxAll" type="checkbox" />All
                        <img class="corner_inset_right" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/corner_inset_right.png"/>
                    </li>
                    <li><input id="Articles" type="checkbox" />Articles</li>
                    <li><input id="Tutorials" type="checkbox" />Tutorials</li>
                    <li><input id="Reviews" type="checkbox" />Reviews</li>
                    <li><input id="Resources" type="checkbox" />Resources</li>
                    <li class="last">
                        <img class="corner_left" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/corner_left.png"/>
                        <img class="middle" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/dot.gif"/>
                        <img class="corner_right" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/corner_right.png"/>
                    </li>
                </ul>
            </li>
        </ul>
        <img style="float:left;" alt="" src="<?=$this->baseUrl();?>/resources/images/vimeo/menu_right.png"/>
</div>
<div style="float:none; clear:both;"></div>
