<div class="unit">
	<div class="container">
	<div class="unit horizontal-center layout on-2 columns">
		<div class="fixed column" style="width:640px;padding-right:20px;">
			<?=$this->action('detail','manager','polling',array('guid'=>$this->pollId)); ?>
			<div style="padding-top:40px;"></div>
			<?=$this->action('poll','manager','polling',array('guid'=>$this->pollId)); ?>
		</div>
		<div class="fixed column" style="width:300px;">
			<?=$this->action('kanan','widgets_sidebar','hol-site'); ?>
		</div>
	</div>
 	</div>
</div>