<div id="poll-container"></div>
<script type="text/javascript">
var total_votes = 0;
var percent;
var votedID = '<?=$this->pollId;?>';

function animateResults(){
  $("#poll-results div").each(function(){
      var percentage = $(this).next().text();
      $(this).css({width: "0%"}).animate({
				width: percentage}, 'slow');
  });
}

<?php
	$queryAttr="SELECT * FROM options WHERE pollGuid ='".$this->pollId."'";
	$db = Zend_Db_Table::getDefaultAdapter()->query($queryAttr);
	$rowset = $db->fetchAll(Zend_Db::FETCH_OBJ);
	
	foreach ($rowset as $row) {
?>

		total_votes = total_votes+parseInt(<?=$row->hits ?>);
		
<?php } ?>

var results_html = "<span class='barjudul'><?=$this->rowPoll->title; ?><br></span><div id='poll-results'><h4>Hasil :</h4><dl class='graph'>";

<?php foreach ($rowset as $row) { ?>
	percent = Math.round((parseInt(<?=$row->hits ?>)/parseInt(total_votes))*100);
	if ('<?=$row->guid ?>' !== votedID) {
		results_html = results_html+"<dt class='bar-title'><?=$row->text ?></dt><dd class='bar-container'><div id='bar<?=$row->guid ?>'style='width:0%;'>&nbsp;</div><strong>"+percent+"%</strong></dd>\n";
	}
	else
	{
		results_html = results_html+"<dt class='bar-title'><?=$row->text ?></dt><dd class='bar-container'><div id='bar<?=$row->guid ?>'style='width:0%;background-color:#0066cc;'>&nbsp;</div><strong>"+percent+"%</strong></dd>\n";
	}
<?php } ?>

results_html = results_html+"</dl><p>Total Votes: "+total_votes+"</p></div>";

$("#poll-container").append(results_html).fadeIn("slow",function(){
	animateResults();
});
</script>