<html>
<head></head>
<body>
<form name="order" method="post" action="http://luna.nsiapay.com/ipg_payment/RegisterOrderInfo">
<input type="hidden" name="TYPE" value="IMMEDIATE">
<input type="hidden" name="BASKET" value="Gold,700000.00,1,700000.00;Administration fee 3%,21000.00,1,21000.00">
<input type="hidden" name="MERCHANTID" value="000100090000028">
<input type="hidden" name="CHAINNUM" value="NA">
<input type="hidden" name="TRANSIDMERCHANT" value="000003">
<input type="hidden" name="AMOUNT" value="20000.00">
<input type="hidden" name="CURRENCY" value="360">
<input type="hidden" name="PurchaseCurrency" value="360">
<input type="hidden" name="acquirerBIN" value="NSIAPAY">
<input type="hidden" name="password" value="123456">
<input type="hidden" name="URL" value="http://www.hukumonline.com/payment/nsiapay_verify.php">
<input type="hidden" name="MALLID" value="199">
<input type="hidden" name="SESSIONID" value="2234567890absdefghijklmnopqrstuvwxyz">
<input type="hidden" name="WORDS" value="dc7d685276ceafcfa91fd43b21d3ce745b9db0a9">
<input type="submit" value="kirim">
</form>
</body>
</html>
