<div style="width:auto;">
    <div class="x-box-tl"><div class="x-box-tr"><div class="x-box-tc"></div></div></div>
    <div class="x-box-ml"><div class="x-box-mr"><div class="x-box-mc">
    	<h3 style="margin-bottom:5px;"><img border="0" height="14" width="14" src="./library/js/extjs/resources/images/default/silk/icons/folder_add.png">&nbsp;More Info ...</h3>
        <div id="moreinfo">
        <table>
        <tr>
        	<td>Total Displayed / Of / Procent</td>
        	<td>:</td>
        	<td>
        	<?php echo $this->rowset->dised_times; ?> / 
        	<?php if ($this->rowset->dis_times == 0) { ?> Unlimited / 
        	<?php } else { 
        		echo $this->rowset->dis_times; ?> / 
        	<?php 
        	} 
	       	$tblPowerban = new Kutu_Core_Orm_Table_Powerban();
	       	$sum = $tblPowerban->sumPowerban();
	       	if ($this->rowset->dised_times <> 0) {
	       		$procdistime = ($this->rowset->dised_times * 100) / $sum;
	       		echo round($procdistime,2)."% (of all banners in list)";
	       	}
	       	else 
	       	{
	       		echo "0%";
	       	}
        	?>
        	</td>
        </tr>
       	<?php
       	if ($this->rowset->type <> 2) {
       	?>
        <tr>
        	<td>Clicks / Procent</td>
        	<td>:</td>
        	<td>
        	<?php echo $this->rowset->visits ?> /
        	<?php if ($this->rowset->visits <> 0) {
        		$procclicktime = ($this->rowset->visits * 100) / $this->rowset->dised_times;
        		echo round($procclicktime,2)."% (of all banners in list)";
        	}
        	else 
        	{
        		echo "0%";
        	}
        	?>
        	</td>
        </tr>
        <?php } ?>
        </table>
        </div>
    </div></div></div>
    <div class="x-box-bl"><div class="x-box-br"><div class="x-box-bc"></div></div></div>
</div>
