<div class="unit" style="border-top: solid 5px #ffcc00;">
		<div class="unit">
			<div class="container" style="background:#3a3a3a;color:white;padding-right:30px;padding-left:30px;padding-top:15px;padding-bottom:2px;">
				<div class="footnote-down">
				<a href="<?=$this->getRootUrl(); ?>" class="footnote">Home</a> |  <a href="<?=$this->getRootUrl(); ?>/tentangkami" class="footnote">Tentang Kami</a>  |   <a href="<?=$this->getRootUrl(); ?>/kodeetik" class="footnote">Kode Etik</a>  |   <a href="<?=$this->getRootUrl(); ?>/mitrakami" class="footnote">Mitra Kami</a> <br />
				 Informasi yang tersedia di<a href="<?=$this->getRootUrl(); ?>" class="footnote"> www.hukumonline.com</a> tidak ditujukan sebagai suatu nasehat hukum,<br />
				 namun hanya memberikan gambaran umum terhadap suatu informasi atau permasalahan hukum yang sedang dihadapi.<br />
				 Akses dan penggunaan situs ini tunduk pada Syarat dan Ketentuan &copy; 2009
				 </div>
			</div>
		</div>
</div>