<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>hukumonline.com Talks</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" />
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/elastic.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/typography.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/vimeo.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/talks.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/jcart.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/fdropdown/dropdown.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/fdropdown/themes/flickr.com/default.ultimate.css" />
	<script src="<?=$this->baseUrl();?>/js/jquery/jquery-1.4.2.min.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
</head>
<body>
	<?=$this->render("header.phtml"); ?>
	<div style="padding-top:20px"></div>
	<?=$this->layout()->content?>
	<?=$this->render("footer.phtml"); ?>
</body>
</html>