<div class="unit">
	<div class="container">
	<div class="unit horizontal-center layout on-2 columns">
		<div class="fixed column" style="width:640px;padding-right:20px;">
			<?php echo $this->action('detail.issue','widgets_catalog','hol-site',array('guid'=>$this->catalogGuid)); ?>
		</div>
		<div class="fixed column" style="width:300px;">
			<?php echo $this->action('kanan','widgets_sidebar','hol-site'); ?>
		</div>
	</div>
 	</div>
</div>