<div class="unit">
	<div class="container">
<!-- zone A1 -->
<div class="unit horizontal-center layout" align="center">

<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=2");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=af95d409&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=2&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=af95d409' border='0' alt='' /></a></noscript>


</div>
	
	<div class="unit horizontal-center layout on-2 columns">
		<div class="fixed column" style="width:640px;padding-right:20px;">
			<?php echo $this->action('detail','widgets_catalog','hol-site',array('guid'=>$this->catalogGuid,'page'=>$this->page)); ?>
		</div>
		<div class="fixed column" style="width:300px;">
			<?//php echo $this->action('kanan','widgets_sidebar','hol-site'); ?>
			<!-- AdJuggler 7 request
			Type: Single Ad
			Ad Placement: News/300x250
			Channel: News
			Ad Size: IMU (Medium Rec Pop-Up,300X250)
			Position: 0
			-->
			<script type="text/javascript" language="JavaScript">
			  aj_server = 'http://adj.adstars.co.id/servlet/ajrotator/'; aj_tagver = '1.0';
			  aj_zone = 'adstars'; aj_adspot = '130529'; aj_page = '0'; aj_dim ='78535'; aj_ch = '123589'; aj_ct = ''; aj_kw = '';
			  aj_pv = true; aj_click = '';
			</script><script type="text/javascript" language="JavaScript" src="http://cdn.hadj7.adjuggler.net/banners/Client84267/1308210017899_ajtg.js"></script>
			
		</div>
	</div>
 	</div>
</div>