<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>hukumonline.com Log In</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/jquery-1.2.3.pack.js"></script>
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/elastic.css" />
	<script src="<?=$this->baseUrl();?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/typography-1.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/validate.css" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.form.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.delegate.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.validate.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.highlightFade.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.pstrength.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/upload/jquery.MultiFile.pack.js"></script>
</head>
<body>
	<div class="unit horizontal-center layout">
		<div class="container" style="padding-top:15px;">
			<img src="<?=$this->baseUrl(); ?>/resources/images/holid.jpg" alt="mnutopshadow" />
			<div style="font-size:10px;padding-top:2px;border-bottom:1px solid #ddd;">Buat Akun HukumonlineID</div>
			<div style="float:right;font-size:12px;">
				<a href="<?=$this->getRootUrl(); ?>">Awal</a> | <a href="<?=$this->baseUrl();?>/identity/daftar">Daftar</a>
			</div>
			<div style="clear:both;"></div>
		</div>
	</div>
	<div style="padding-top:10px;"></div>
	<div class="container">
		<div class="unit horizontal-center layout">
			<h2>.:accounts</h2>
		</div>
	</div>
	<div style="padding-top:15px;"></div>
	<div class="container">
		<div class="unit horizontal-center layout on-2 columns" style="padding-bottom:20px;">
			<div class="fixed column" style="width:750px;">
				<?=$this->layout()->content;?>
			</div>
			<div class="fixed column" style="width:200px;">
				<ul id="psetting">
					<li>
						<h3>My <i>Dashboard</i></h3> 
						<a href="<?=$this->baseUrl();?>/identity/personal.setting">Dashboard</a>
					</li>
					<li>
						<h3 style="padding-bottom:5px;">Manage <i>Profile</i></h3>
						<a href="<?=$this->baseUrl();?>/identity/editprofile">edit Profile</a><br>
						<a href="<?=$this->baseUrl();?>/identity/picture">Foto</a><br>
						<!-- <a href="/identity/changeusername">ubah Username</a><br> -->
						<a href="<?=$this->baseUrl();?>/identity/change.password">ubah Password</a><br>
						<a href="<?=$this->baseUrl();?>/identity/changeemail">ubah Email</a>
					</li>
					<li>
						<h3 style="padding-bottom:5px;">Laporan</h3>
						<a href="<?=$this->baseUrl();?>/store/payment/list">Order History</a><br>
						<a href="">Transaction History</a><br>
						<a href="<?=$this->baseUrl();?>/identity/payment/confirm">Payment Confirmation</a><br>
						<a href="">Edit Billing Info</a>
					</li>
					<li>
						<h3>My <i>Documents</i></h3>
						<a href="">View All</a>
					</li>
					<li>
						<h3 style="padding-bottom:5px;">Subscription</h3>
						<a href="">Newsletter</a><br>
						<a href="">Blackberry Notification</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
	
	
	<div class="unit">
		<div class="container footer">
		<a href="<?=$this->baseUrl();?>/identity/feedback">Feedback</a> | Copyright &copy; 2008 Hukumonline		
		</div>
	</div>
</body>
</html>