<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>hukumonline.com Log In</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/jquery-1.2.3.pack.js"></script>
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/elastic.css" />
	<script src="<?=$this->baseUrl();?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/typography-1.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/validate.css" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.form.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.delegate.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.validate.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.highlightFade.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/form/jquery.pstrength.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/upload/jquery.MultiFile.pack.js"></script>
</head>
<body>
	<div class="unit horizontal-center layout" id="content">
		<div class="container" style="padding-top:15px;">
		<img src="<?=$this->baseUrl(); ?>/resources/images/holid.jpg" alt="mnutopshadow" />
		<div style="font-size:10px;padding-top:2px;border-bottom:1px solid #ddd;">Buat Akun HukumonlineID</div>
		<div style="padding-top:20px;"></div>
		<?=$this->layout()->content;?>
		</div>
	</div>
	<div id="ft">
	<div class="unit">
		<div class="container footer">
		<a href="<?=$this->baseUrl();?>/identity/feedback">Feedback</a> | <a href="http://hukumonline.blogspot.com/">Blog</a> | Copyright &copy; 2008 Hukumonline		
		</div>
	</div>
	</div>
</body>
</html>