<!-- zone topA1 -->
<?php if ($this->isBannerExist('6247')) { ?>
<div class="unit horizontal-center layout on-2 columns">
	<div class="fixed column" style="width:647px;"><?=$this->action('view','banner','hol-site',array('zid'=>'6247')); ?></div>
	<div class="fixed column" style="width:310px;height:90px;"><?=$this->action('view','banner','hol-site',array('zid'=>'2046')); ?></div>
</div>
<div style="padding-top:5px;"></div>
<?php 
} 
// zone topA2 
else if ($this->isBannerExist('2046'))
{
?>
<div class="unit horizontal-center layout on-2 columns">
	<div class="fixed column" style="width:647px;"><?=$this->action('view','banner','hol-site',array('zid'=>'6247')); ?></div>
	<div class="fixed column" style="width:310px;height:90px;"><?=$this->action('view','banner','hol-site',array('zid'=>'2046')); ?></div>
</div>
<div style="padding-top:5px;"></div>
<?php 
} 
// zone topA3 
else if ($this->isBannerExist('6641'))
{
?>
<div class="unit horizontal-center layout">
<?php 
	echo $this->action('view','banner','hol-site',array('zid'=>'6641'));
?>
</div>
<div style="padding-top:5px;"></div>
<?php 
}
?>
<div class="unit horizontal-center layout on-2 columns">
<div class="fixed column" style="width:310px">
	<?=$this->action('utama','widgets_content','hol-site');?>
	<div class="bersih"></div>
	<div style="padding-top:5px;"></div>
	<!-- zone middleA -->
	<?php if ($this->isBannerExist('4322')) {
		$this->action('view','banner','hol-site',array('zid'=>'4322')); 
	?>
	<div style="padding-top:5px;"></div>
	<?php } ?>
	<?=$this->action('fokus','widgets_content','hol-site');?>
</div>
<div class="fixed column" style="width:650px;">
	<div class="container">
		<div class="unit on-2 columns">
			<div class="fixed column" style="width:330px;padding-left:5px;">
			<?=$this->action('terbaru','widgets_content','hol-site');?>
			<div class="bersih"></div>
			<div style="padding-top:5px;"></div>
			<?=$this->action('isuhangat','widgets_content','hol-site');?>
			</div>
			<div class="fixed column" style="width:308px;padding-left:5px;">
			<?=$this->action('klinik','widgets_content','hol-site');?>
			<div class="bersih"></div>
			<div style="padding-top:2px;">&nbsp;</div>
			<!-- zone middleB -->
			<?=$this->action('view','banner','hol-site',array('zid'=>'4304')); ?>
			<!-- ADMAX Network Ad spot Tag 
			Publisher : PT. Justika Siar Publika 
			Section : ROS 
			Ad spot : ID/www.hukumonline.com/ROS/300x250 
			Ad spot Code: 435289 
			Ad Dimension : 300 x 250 - 300x250 IMU (Medium Rectangle) 
			Ad spot URL : http://www.hukumonline.com/ 
			 
			<script language=JavaScript
			src="http://a.admaxserver.com/servlet/ajrotator/435289/0/vj?z=admaxasia2&dim=280733&pid=47db15c7-dce8-46be-909d-3a7beb32a2d4&asid=10532168-4527-4ca0-afd1-1e98a29632c5"></script><noscript><a
			href="http://a.admaxserver.com/servlet/ajrotator/435289/0/cc?z=admaxasia2&pid=47db15c7-dce8-46be-909d-3a7beb32a2d4&asid=10532168-4527-4ca0-afd1-1e98a29632c5"><img
			src="http://a.admaxserver.com/servlet/ajrotator/435289/0/vc?z=admaxasia2&dim=280733&pid=47db15c7-dce8-46be-909d-3a7beb32a2d4&asid=10532168-4527-4ca0-afd1-1e98a29632c5&abr=$imginiframe"
			width="300" height="250" border="0"></a></noscript> -->
			</div>
		</div>
	</div>
</div>
</div>
<!-- zone middleB2 -->
<?php if ($this->isBannerExist('1713')) { ?>
<div class="unit horizontal-center layout on-3 columns" style="padding-top:5px;">
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'1713')); ?></div>
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'3017')); ?></div>
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'7116')); ?></div>
</div>
<?php 
} 
// zone middleB3 
else if ($this->isBannerExist('3017'))
{
?>
<div class="unit horizontal-center layout on-3 columns" style="padding-top:5px;">
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'1713')); ?></div>
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'3017')); ?></div>
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'7116')); ?></div>
</div>
<?php 
} 
// zone middleB4 
else if ($this->isBannerExist('7116'))
{
?>
<div class="unit horizontal-center layout on-3 columns" style="padding-top:5px;">
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'1713')); ?></div>
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'3017')); ?></div>
	<div class="fixed column" style="width:320px;"><?=$this->action('view','banner','hol-site',array('zid'=>'7116')); ?></div>
</div>
<?php 
} 
// zone middleB1 
else if ($this->isBannerExist('3515'))
{
?>
<div class="unit horizontal-center layout" style="padding-top:5px;">
<?php 
	echo $this->action('view','banner','hol-site',array('zid'=>'3515'));
?>
</div>
<?php 
}
?>
<div class="unit horizontal-center layout">
	<div class="pembatas">
		<img src="resources/images/line_yellow.jpg" width="10" height="14" />
	</div>
</div>
<div class="unit horizontal-center layout on-2 columns">
<div class="fixed column" style="width:310px;">
	<div class="td_peraturan1">
		<div class="judulnaik">
			<h1>Pusat Data hukumonline</h1>
		</div>
		<div class=c-isi>
			<p>Hukumonline Legal Directory (HOLD) Online memuat koleksi data hukum elektronik terlengkap di Indonesia.</p>
			<div style="padding-top:15px;"></div>
			<a href="javascript:;" class="peraturan">Selengkapnya</a>
			<div class="pdh">
				<ul id="listnoline">
					<li><img src="resources/images/arrow02.jpg" width="9" height="9" /><a href="<?=$this->getRootUrl(); ?>/pusatdata" class="peraturan"> Browse</a></li>
					<li><img src="resources/images/arrow02.jpg" width="9" height="9" /><a href="<?=$this->getRootUrl(); ?>/pusatdata/advanced_search" class="peraturan"> Advance Search</a></li>
					<li><a href="http://identity.hukumonline.com/identity/daftar" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('signup','','resources/images/signupnow_f2.jpg',1)"><img src="resources/images/signupnow.jpg" alt="Sign up Now !" name="signup" width="217" height="89" border="0" id="signup" /></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<div class="fixed column" style="width:650px;">
	<div class="container">
		<div class="unit on-2 columns">
			<div class="fixed column" style="width:365px;padding-left:5px;">
				<div class="td_peraturan3">
					<div id="lilmenu">
						<div class="mati" title="peraturanterbaru"><span>Dokumen Terbaru</span></div>
						<div class="hidup" title="peraturanpilihan"><span>Pilihan</span></div>
					</div>
					<div id="peraturanterbaru" class="tutup">
					<?=$this->ajaxActionRenderer(ROOT_URL.'/peraturan');?>
					</div>
			        <div id="peraturanpilihan" class="buka">
			        <?=$this->action('peraturanpilihan','widgets_content','hol-site'); ?>
			       	</div>
		       	</div>
			</div>
			<div class="fixed column" style="width:268px;padding-left:5px;">
			<div class="iklanrol">
				<div style="height:320px;">
            		<div id="dog1" class="tabcontent"> 
            		<a href="javascript:;"><img src="resources/images/kumon/bannermarketing1.jpg" /></a>
            		</div>
          			<div id="dog2" class="tabcontent"> 
            		<a href="javascript:;"><img src="resources/images/kumon/bannermarketing3.jpg" /></a>
          			</div>
          			<div id="dog3" class="tabcontent"> 
            		<a href="javascript:;"><img src="resources/images/kumon/ppminerbaban.jpg" /></a>
          			</div>
          			<div id="dog4" class="tabcontent"> 
            		<a href="javascript:;"><img src="resources/images/kumon/bannermarketing4.jpg" /></a>
          			</div>
				</div>
            	<div id="pettabs" class="indentmenu">
              	<ul>
	                <li><a href="javascript:;" rel="dog1" class="selected">1</a></li>
	                <li><a href="javascript:;" rel="dog2">2</a></li>
	                <li><a href="javascript:;" rel="dog3">3</a></li>
	                <li><a href="javascript:;" rel="dog4">4</a></li>
              	</ul>
              	<br style="clear: left" />
            	</div>
          		<script type="text/javascript">
					var mypets=new ddtabcontent("pettabs")
					mypets.setpersist(true)
					mypets.setselectedClassTarget("link")
					mypets.init(5000)
    			</script>
			</div>
			<div class="bersih"></div>
			</div>
		</div>
	</div>
</div>
</div>
<div class="unit horizontal-center layout">
	<div class="pembatas"><img src="resources/images/line_yellow.jpg" height="14" /></div>
</div>
<div class="unit horizontal-center layout on-2 columns">
<div class="fixed column" style="width:460px;">
	<?=$this->action('kolom','widgets_content','hol-site');?>
</div>
<div class="fixed column" style="width:500px;">
	<div class="container">
		<div class="unit on-2 columns">
			<div class="fixed column" style="width:250px;padding-left:5px;">
			<?=$this->action('tokoh','widgets_content','hol-site');?>
			</div>
			<div class="fixed column" style="width:240px;padding-left:5px;">
			<?=$this->action('resensi','widgets_content','hol-site');?>
			</div>
		</div>
	</div>
</div>
</div>
<div class="bersih"></div>
<div class="unit horizontal-center layout on-4 columns">
<div class="fixed column" style="width:235px;padding-top:5px;">
	<?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb9','title'=>'Info'));?>
</div>
<div class="fixed column" style="width:235px;padding-top:5px;padding-left:5px;">
	<?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb14','title'=>'Jeda'));?>
</div>
<div class="fixed column" style="width:235px;padding-top:5px;padding-left:5px;">
	<?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb18','title'=>'Tajuk'));?>
</div>
<div class="fixed column" style="width:240px;padding-top:5px;padding-left:5px;">
	<?=$this->action('view','manager','polling');?>
</div>
</div>
<!-- zone bottomA1 -->
<?php if ($this->isBannerExist('3576')) { ?>
<div class="unit horizontal-center layout on-4 columns" style="padding-top:5px;">
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'3576')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'2769')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'4406')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'7613')); ?></div>
</div>
<?php 
} 
// zone bottomA2 
else if ($this->isBannerExist('2769'))
{
?>
<div class="unit horizontal-center layout on-4 columns" style="padding-top:5px;">
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'3576')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'2769')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'4406')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'7613')); ?></div>
</div>
<?php 
} 
// zone bottomA3 
else if ($this->isBannerExist('4406'))
{
?>
<div class="unit horizontal-center layout on-4 columns" style="padding-top:5px;">
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'3576')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'2769')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'4406')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'7613')); ?></div>
</div>
<?php 
} 
// zone bottomA4
else if ($this->isBannerExist('7613'))
{
?>
<div class="unit horizontal-center layout on-4 columns" style="padding-top:5px;">
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'3576')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'2769')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'4406')); ?></div>
	<div class="fixed column" style="width:250px;"><?=$this->action('view','banner','hol-site',array('zid'=>'7613')); ?></div>
</div>
<?php 
} 
// zone bottomA5 
else if ($this->isBannerExist('2707'))
{
?>
<div class="unit horizontal-center layout" style="padding-top:5px;">
<?php 
	echo $this->action('view','banner','hol-site',array('zid'=>'2707'));
?>
</div>
<?php 
}
?>
