<?php if ($this->aData['totalCount'] != 0) { ?>
<div id='catalogContent'></div><br>
<table>
	<tr>
		<td width=25%>&nbsp;</td>
		<td align="center"><div id='catalogPagination' class="pagination"></div></td>
	</tr>
</table>


<script>

$(document).ready(function(){
	
	var isFirstTime = 1;
	
	var myPageIndex = 0;
	
	$("#catalogPagination").pagination(<?=$this->aData['totalCount'];?>, 
	{items_per_page:<?=$this->aData['limit'];?>, callback:handlePaginationClick, next_text:'Berikutnya',prev_text:'Sebelumnya'}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		myPageIndex = new_page_index;
		myStart = (<?=$this->aData['limit'];?> * myPageIndex);
		
		if(true)
		{
			if($('#tblCatalogPager-'+myPageIndex).length==0)
			{
				$('#message_box').show();
				$.getJSON('<?=$this->getRootUrl();?>/klinik/kategoriklinik/<?=$this->aData['catalogGuid'];?>/'+myStart+'/<?=$this->aData['limit'];?>', '', klinikResult);
			}
			else
				showCatalogContent();
		}
		return false;
	}
	
	function klinikResult(res)
	{
		size = res.klinikkategori.length;
		var tblRow = "<a name='a-"+myPageIndex+"' ></a>"+'<table class="tblCatalogPager" id="tblCatalogPager-'+myPageIndex+'">';
		for(i=0;i<size;i++)
		{
			tblRow += 
				
				"<tr valign=top>"
				+"<td class='klideisi'><h2><span class=kategori>"+res.klinikkategori[i].kategori+"</span>&nbsp;<a href='<?=$this->getRootUrl(); ?>/klinik/detail/"+res.klinikkategori[i].guid+"'>"+res.klinikkategori[i].title+"</a></h2>"
				+"<div class='q2'>Pertanyaan :</div>"
				+"<p>"+res.klinikkategori[i].pertanyaan+"</p>"
				+"<div class='author'>"+res.klinikkategori[i].createdBy+"<br>"
				+res.klinikkategori[i].author+"<br>"
				+res.klinikkategori[i].sumber+"<br>"
				+"</div>"
				+"</td>"
				+"</tr>";
				
		}
		tblRow += "</table>";
		$(tblRow).appendTo("#catalogContent");
		showCatalogContent();
		$('#message_box').fadeOut();
	}
	function showCatalogContent()
	{
		$('.tblCatalogPager').hide();
		$('#tblCatalogPager-'+myPageIndex).show();
		if(!isFirstTime)
			Scroller.scroll();
		isFirstTime = 0;
	}
	
	
});



</script>
<?php } else { ?>
<span style="font:12px verdana,arial,helvetica,sans-serif;">Kategori klinik kosong</span>
<?php } ?>