<?php if ($this->numberOfRows == 0) { ?>
<span style="font:12px verdana,arial,helvetica,sans-serif;">Tidak ada klinik</span>
<?php } ?>
<div class="klinikterbaruisi">
<?php for ($i=0;$i<$this->numberOfRows;$i++) { ?>
<h2><span class="kategori"><?=$this->data[$i][2];?></span>&nbsp;<a href="<?=$this->baseUrl(); ?>/klinik/detail/<?=$this->data[$i][3];?>"><?=$this->data[$i][0];?></a></h2>
<p><?=$this->data[$i][1];?></p>
<div class="author">Penanya: <?=$this->data[$i][4];?></div>
<?php } ?>
</div>
