<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?=$this->pageTitle; ?></title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/jquery-1.2.3.pack.js"></script>
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/elastic.css" />
	<script src="<?=$this->baseUrl();?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/typography.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/tabcontent.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/calender.css" />
	<link rel="stylesheet" href="<?=$this->baseUrl();?>/resources/css/superfish.css" type="text/css" media="screen, projection" />
	<script src="<?=$this->baseUrl();?>/js/jquery/newsticker/jquery.newsticker.pack.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/superfish/hoverIntent.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/superfish/superfish.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl(); ?>/js/tabcontent.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl(); ?>/js/globe.js" type="text/javascript"></script>
	<script type="text/javascript">

		// initialise plugins
		$(document).ready(function(){
			jQuery('ul.sf-menu').superfish();
		});

	</script>
</head>
<body>
	<?=$this->render("headerkategori.phtml"); ?>
	<div style="padding-top: 5px"></div>
	<?=$this->layout()->content?>
	<?=$this->render("footer.phtml"); ?>
</body>
</html>