<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<title>hukumonline.com - Berita : <?=$this->getCatalogTitle($this->catalogGuid); ?></title>
	<meta property="og:title" content="<?=$this->getCatalogTitle($this->catalogGuid);?>"/>
	<?=$this->getImage($this->catalogGuid);?>
	<meta property="og:description" content="<?=$this->getCatalogAttribute($this->catalogGuid,"fixedDescription");?>"/>
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" type="image/x-icon" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/BBCode.js"></script>
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/jquery-1.2.3.pack.js"></script>
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/elastic.css" />
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/js/jquery/paging/pagination.css" />
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/tabcontent.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/calender.css" />	
	<script src="<?=$this->baseUrl();?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/typography.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/nlok.css" />
	<script src="<?=$this->baseUrl();?>/js/jquery/form/jquery.form.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/form/jquery.delegate.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/form/jquery.validate.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/newsticker/jquery.newsticker.pack.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/paging/jquery.pagination.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/fontsizer/jquery.jfontsizer.packed.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/tabcontent.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl();?>/js/globe.js" type="text/javascript"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#fontsizer').jfontsizer({
				applyTo: '#detailarticle',
				changesmall: '2',
				changelarge: '2',
				expire: 30
			});
			$('.formkomentar').eq(0).show();
			$komentar = $('#komentar');
			$('.togglereply').each(function(index) {
				$(this).click(function() {
					if($('.togglereply').eq(index).text()=='Batalkan'){
						$('.disclaimer').after($komentar);
						$('.togglereply').eq(index).text('Balas Tanggapan');
						$('.commentID').val(0);
					} else {
						$('.togglereplychild').eq(index).after($komentar);
						$('.togglereply').text('Balas Tanggapan').eq(index).text('Batalkan');
							$theId = $('.togglereply').eq(index).attr('id').split('-');
						$('.commentID').val($theId[1]);
					}
				});
			});
			$('.togglechild').each(function(index) {
				$(this).click(function() {
					if($(this).hasClass('childclose')) {
						$('.childcomments').hide();
						$('.togglechild').removeClass('childclose');
					} else {
						$('.childcomments').hide().eq(index).show();
						$('.togglechild').removeClass('childclose');
						$(this).addClass('childclose');
					}
					return false;
				});
			});
			$guid = '<?=$this->catalogGuid; ?>';
			getRating($guid);
			function getRating(guid)
			{
				$.ajax({
					type:"GET",
					dataType:'json',
					url:"<?=$this->getRootUrl(); ?>/getrate",
					data:"guid="+guid,
					cache:false,
					async:false,
					success: function(result) {
						if (result.error == -1) {
							$('#ratelinks').remove();
							$("#current-rating-"+guid+"").css({ width: "" + result.data + "%" });
						}
						else
						{
							$("#current-rating-"+guid+"").css({ width: "" + result.data + "%" });
						}
					},
					error: function(result) {
						alert("some error occured, please try again later");
					}	
				});
			}
			// link handler
			$('#ratelinks li a').click(function(){
				$.ajax({
					type: "GET",
					dataType: 'json',
					url: "<?=$this->baseUrl(); ?>/rate",
					data: "rating="+$(this).text()+"&guid="+$guid,
					cache: false,
					async: false,
					success: function(result) {
						if (result.error == -1) {
							$("#ratelinks").remove();
							$('.votitaly-box').append(result.message);
						}
						else
						{
							// remove #ratelinks element to prevent another rate
							$("#ratelinks").remove();
							// get rating after click
							getRating($guid);
							// then update it
							$('.votitaly-box').empty();
							$('.votitaly-box').html(result.message);
						}
					},
					error: function(result) {
						alert("some error occured, please try again later");
					}
				});
			});
			Recaptcha.create("<?=$this->getCaptcha('public');?>",
				"recaptcha_div",
				{
					theme:"white"
				}	
			);
		});
	</script>
	<style type="text/css">
	.messagebox 		{position:absolute;width:100px;margin-left:30px;border:1px solid #c93;background:#ffc;padding:3px;font-family:verdana;font-size:12px }
	.messageboxok 		{position:absolute;width:auto;margin-left:30px;border:1px solid #349534;background:#C9FFCA;padding:3px;font-weight:bold;color:#008000;}
	.messageboxerror 	{position:absolute;width:auto;margin-left:30px;border:1px solid #CC0000;background:#F7CBCA;padding:3px;font-weight:bold;color:#CC0000;}
	form.rfgform label.error, label.error {
		/* remove the next line when you have trouble in IE6 with labels in list */
		display: none;
		color: red;
		font-family: verdana;
		font-size: 12px;
	}
	div.cc {
		background-color: #eee;
		border: 1px solid red;
	}
	div.cc ol li {
		list-style:none;
		margin-left: 20px;
		margin-bottom:5px;
	}
	div.cc { display: none; }
	.cc label.error {
		display: inline;
	}
	.lineThrough{
		text-decoration:line-through;	
	}
	</style>
</head>
<body>
	<?=$this->render("header.phtml"); ?>
	<div style="padding-top:10px;"></div>
	<?=$this->layout()->content; ?>
	<?=$this->render("footer.phtml"); ?>
	
	<script type="text/javascript" src="http://static.ak.fbcdn.net/connect.php/js/FB.Share"></script>

	<script type="text/javascript">
	
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	
	</script>
	
	<script type="text/javascript">
	
	try{
	
	var pageTracker = _gat._getTracker("UA-2695772-1");
	
	pageTracker._trackPageview();
	
	} catch(err) {}
	
	</script>	
</body>
</html>