<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?=$this->pageTitle; ?></title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" />
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/elastic.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/typography-min.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/easynews-min.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/tabcontent-min.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/calender-min.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/graph-min.css" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/jquery-1.2.3.pack.js"></script>
	<script src="<?=$this->baseUrl();?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
	<script src="<?=$this->baseUrl();?>/js/jquery/newsticker/jquery.newsticker.pack.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl(); ?>/js/jquery/news/jquery.easynews.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl(); ?>/js/lilmenu-min.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl(); ?>/js/tabcontent.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl(); ?>/js/globe-min.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl(); ?>/js/hoverbutton-min.js" type="text/javascript"></script>
</head>
<body onload="lilmenu.init();">
	<?=$this->render("header.phtml"); ?>
	<div style="padding-top: 5px"></div>
	<?=$this->layout()->content?>
	<?=$this->render("footer.phtml"); ?>
</body>
</html>