<div id="detailFooter">
	<div id="blokWadah">
		<div id="blokTitle">
		tanggapan
		</div>
		<div id="blokIsi">
			<?php 
			echo $this->action('list4','manager','comment',array('guid'=>$this->catalogGuid)); 
			// echo $this->action('list3','widgets_comment','hol-site',array('guid'=>$this->catalogGuid)); 
			// echo $this->action('list2','widgets_comment','hol-site',array('guid'=>$this->catalogGuid,'page'=>$this->page)); 
			// echo $this->action('list','widgets_comment','hol-site',array('guid'=>$this->catalogGuid,'page'=>$this->page)); 
			?>
			<div class="disclaimer"><a href="http://dapur.detik.com/content/disclaimer">disclaimer</a></div><br />
			<div id="komentar">
			<div id="blokIsiKomen">
				<div id="blokIsiProfilTitle">Kirim Tanggapan</div>
				<div id="hr" style="border-bottom:1px solid #eee"></div>
				<div id="divClear"></div>
				<div class="formkomentar">
				<!-- our error cc -->
				<div class="cc">
					<ol>
						<li></li>
					</ol>
				</div>
				<form id="tanggapan" style="margin:0;padding:0;width:70%;">
					<input type="hidden" name="guid" id="guid" value="<?php echo $this->catalogGuid; ?>">
					<input type="hidden" name="parent_id" class="commentID" value="0" />
					<div id="divLeft">
						Nama<br><input type="text" size="45" maxlength="255" name="name" id="name" style="width:252px;" />
					</div>
					<div id="divClear"></div>
					<div id="divLeft">
						Email<br><input type="text" size="45" maxlength="255" name="email" id="email" style="width:252px;" />
					</div>
					<div id="divClear"></div>
					<div id="divLeft">
						Judul<br><input type="text" size="45" maxlength="255" name="title" id="title" style="width:252px;" />
					</div>
					<div id="divClear"></div>
					<?php echo $this->bbCodeCP; ?>
					<div id="divLeft">
						Tanggapan<br><textarea cols="40" rows="8" name="comment" id="comment" onFocus="javascript:document.theField=this.name;" style="width:252px;"></textarea>
					</div>
					<div id="divClear"></div>
					<div id="parsecomment"></div>
					<div style="padding:0;margin:0;"></div>
					<input type="submit" name="submitComment" id="submitComment" value="Kirim"  />&nbsp;<input type="button" name="preview" id="preview" value="Preview Tanggapan" /><span id="msgbox" style="display:none"></span>
				</form>
				<script type="text/javascript">
				setTimeout(function(){
					var cc = $('div.cc');
					$.validator.setDefaults({
						submitHandler: function(){
							var options = {
								 type:'post'
								,dataType:'json'
								,url:'<?php echo $this->getRootUrl(); ?>/comment/save'
								,beforeSubmit:prepareData
								,success:function(response){
									if (response.success == true)
									{
										$('#msgbox').fadeTo(200,0.1,function(){
											$(this).html('Terima kasih atas tanggapan anda').addClass('messageboxok').fadeTo(900,1,
											function(){
												location.reload(true);
											});
										});
									}
									else
									{
										
									}
								}
							};
							$('#tanggapan').ajaxForm(options);
						}
					});
					$('#tanggapan').validate({
						errorContainer: cc,
						errorLabelContainer: $("ol", cc),
						wrapper: 'li',
						meta: "validate",
						rules:{
							 name:'required'
							,email:{
								 required:true
								,email:true
							}
							,title:'required'
							,comment:'required'
						},
						messages:{
							 name: "Masukan nama anda!"
							,email: "Masukan email anda / penulisan email salah!"
							,title: "Masukan judul tanggapan!"
							,comment: "Masukan tanggapan anda!"
						}
					});
					function prepareData()
					{
						$("#msgbox").removeClass().addClass('messagebox').text('Simpan ...').fadeIn(1000);
					}
					$('#preview').click(function(){
						var res = $('#comment').attr('value');
						$("#parsecomment").empty();
						$.ajax({
							type: 'POST'
							,dataType: 'json'
							,url: '<?php echo $this->getRootUrl(); ?>/parsecomment'
							,data:'content='+ res
							,success: function(json) {
								if( json.success == true ) {
									var html = json.data;
									$("#parsecomment").append(html);
								} 
							}
						});
					});
					
				});
				</script>		
				</div>		
			</div>
			</div>
			<?php if(!$this->isLoggedIn) : ?>
			<div id="blokIsiKomen">
				Jika anda member Hukumonline, silahkan <b><a href="<?php echo $this->loginUrl;?>">login</a></b>, atau <b><a href="<?php echo $this->signUp;?>">Daftar</a></b> ID anda. 	
			</div>
			<?php endif; ?>
		</div>
	</div>
</div>