<?php if (!$this->paginator) { ?>
<div id="blokIsiKomen">
	Belum ada tanggapan untuk ditampilkan pada artikel ini.
</div>
<?php } else { ?>
<table style="width:100%;">
  <tr>
    <td>
	<div id="jc">
	<div id="comments">
	<div class="comments-lists" id="comments-list-0">
<?php 
		$i = 0;
		
		$count = count($this->paginator);
		$currentLevel = 0;
		
		foreach ($this->paginator as $id => $comment) {
			if ($currentLevel < $comment->level) {
?>		
	</div>
	<div class="comments-list" id="comments-list-<?php echo $comment->getParent(); ?>">
<?php 
			} else {
				$j = 0;
	
				if ($currentLevel >= $comment->level) {
					$j = $currentLevel - $comment->level;
				} else if ($comment->level > 0 && $i == $count - 1) {
					$j = $comment->level;
				}

				while($j > 0) {
?>
	</div>
<?php
					$j--;
				}
			}
?>
	<div class="<?php echo ($i%2 ? 'odd' : 'even'); ?>" id="comment-item-<?php echo $id; ?>">	
	<div id="blokIsiKomen">			
		<div class="comment-avatar"><img src="<?php $this->baseUrl();?>/resources/images/gravatar-140.png" alt="" border="0" /></div>
		<div class="comment-box">
			<div class="avatar-indent">
				<span class="comment-title"><?php echo $comment->getTitle();?></span> &mdash;
				<span class="comment-author"><?php echo $comment->getName();?></span>
				<span class="comment-date"><?php echo Pandamp_Lib_Formater::get_date($comment->getDate());?></span>
				<div class="comment-body"><?php echo Pandamp_Lib_Bbcode::parseBBCode($comment->getComment()); ?></div>
				<div class="togglereplychild">
					<a href="#" class="togglechild">2 Tanggapan</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#comment-<?php echo $comment->getId();?>" id="reply-<?php echo $comment->getId();?>" class="togglereply" onclick="return false">Balas Tanggapan</a>
				</div>
			</div>
		</div>
		<div id="divClear"></div>
	</div>
<?php

			if ($comment->children == 0) {
?>
	</div>
<?php
			}
				
			if ($comment->level > 0 && $i == $count - 1) {
				$j = $comment->level;
			}

			while($j > 0) {
?>				
	</div>
<?php 	
				
               	$j--;
			}

			$i++;
			$currentLevel = $comment->level;
		}
?>				
	</div>
    </td>
  </tr>
	<tr>
		<td style="padding: 5px;" class="copage" nowrap>
		<b>Halaman: </b>
		<?php 
			/*
			 * Print the pagination of type
			 */
			echo $this->paginationControl($this->paginator,
		                                    'Sliding',
		                                    '/partials/user_pagination_control.phtml'); ?>	 dari total <b><?php echo count($this->paginator); ?></b> halaman
		</td>
	</tr>
  
</table>
<?php 	
}
?>

