<?php if (!$this->rows) { ?>
<div id="blokIsiKomen">
	Belum ada tanggapan untuk ditampilkan pada artikel ini.
</div>
<?php } else { ?>
<div id="tcom">
<table style="width:100%">
	<tbody id="tbody">
  <tr>
    <td>
	<div id="jc">
	<div id="comments">
	<div class="comments-lists" id="comments-list-0">
<?php 
		$i = 0;
		
		$count = count($this->rows);
		$currentLevel = 0;
		
		foreach ($this->rows as $id => $comment) {
			if ($currentLevel < $comment->level) {
?>		
	</div>
	<div class="comments-list" id="comments-list-<?php echo $comment->getParent(); ?>">
<?php 
			} else {
				$j = 0;
	
				if ($currentLevel >= $comment->level) {
					$j = $currentLevel - $comment->level;
				} else if ($comment->level > 0 && $i == $count - 1) {
					$j = $comment->level;
				}

				while($j > 0) {
?>
	</div>
<?php
					$j--;
				}
			}
?>
	<div class="<?php echo ($i%2 ? 'odd' : 'even'); ?>" id="comment-item-<?php echo $id; ?>">	
	<div id="blokIsiKomen">			
		<div class="comment-avatar"><img src="<?php $this->baseUrl();?>/resources/images/gravatar-140.png" alt="" border="0" /></div>
		<div class="comment-box">
			<div class="avatar-indent">
				<span class="comment-title"><?php echo $comment->getTitle();?></span> &mdash;
				<span class="comment-author"><?php echo $comment->getName();?></span>
				<span class="comment-date"><?php echo Pandamp_Lib_Formater::get_date($comment->getDate());?></span>
				<div class="comment-body"><?php echo Pandamp_Lib_Bbcode::parseBBCode($comment->getComment()); ?></div>
				<div class="togglereplychild">
					<a href="#" class="togglechild">2 Tanggapan</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="#comment-<?php echo $comment->getId();?>" id="reply-<?php echo $comment->getId();?>" class="togglereply" onclick="return false">Balas Tanggapan</a>
				</div>
			</div>
		</div>
		<div id="divClear"></div>
	</div>
<?php

			if ($comment->children == 0) {
?>
	</div>
<?php
			}
				
			if ($comment->level > 0 && $i == $count - 1) {
				$j = $comment->level;
			}

			while($j > 0) {
?>				
	</div>
<?php 	
				
               	$j--;
			}

			$i++;
			$currentLevel = $comment->level;
		}
?>				
	</div>
    </td>
  </tr>
  </tbody>
</table></div>
<ul id="pagination">
	<?php echo $this->pagination; ?>
</ul>
<script type="text/javascript">
$(function(){
	$('#tbody').ajaxStart(function(){
		$(this).empty().fadeOut('slow').append('<p id="loading">&nbsp;</p>'); // Sebelum : kosongkan isi tbody
	}).ajaxStop(function(){
		$(this).fadeIn('slow'); // Setelah : tampilkan tbody dengan isi yang baru
	});
	// Fungsi pagination
	$('#pagination li a').click(function(){ // Bila link yang ada di <li> dari <ul id="pagination"> diklik, maka lakukan :
		$.ajax({ // Gunakan fungsi ajax JQuery
			type: 'POST', // Pakai metode POST, salah satu alasannya agar pagination tetap bekerja apabila javascript tidak aktif
			url:'<?php echo $this->getRootUrl(); ?>/comment/list',
			data: 'page=' + $(this).attr('rev') + '&guid=<?php echo $this->catalogGuid ?>', // Data yang diambil adalah dari attribut rev (<a href="" title="" rev="">)
			success: function(data){ // Bila ajax berhasil dilakukan, lanjutkan dengan :
			$('#tcom').empty().append(data); 
			}
		});
		return false;
	});
});
</script>
<?php 	
}
?>

