<fieldset>
	<legend>Disclaimer</legend>
	<div class="klinikterbaruisi">
	<p style="text-align:justify;padding-right:10px;">
	Seluruh informasi dan data yang disediakan dalam Klinik hukumonline.com adalah bersifat umum dan disediakan untuk 
	tujuan pendidikan saja. Dengan demikian tidak dianggap sebagai suatu nasehat hukum. Pada dasarnya Klinik hukumonline.com 
	tidak menyediakan informasi yang bersifat rahasia dan hubungan klien - penasehat hukum tidak terjadi.
	Untuk suatu nasehat hukum yang dapat diterapkan pada kasus yang Anda hadapi, Anda dapat menghubungi seorang penasehat 
	hukum yang berpotensi.
	</p>
	</div>
</fieldset>
