<div class="unit horizontal-center layout">
<h2 style="font-weight:bold;">Payment Confirmation</h2>
<div class="bor"></div>
<div style="padding-top:15px;"></div>
<?if(!empty($this->sended)):?>
<h3><?=$this->sended?></h3>
<?endif;?>

<a href="<? echo ROOT_URL;?>/identity/personal.setting">My Account</a> || 
<a href="<? echo ROOT_URL;?>/store/payment/list">Order </a> || 
<a href="<? echo ROOT_URL;?>/store/payment/transaction">Transaction </a> || 
<a href="<? echo ROOT_URL;?>/store/payment/confirm">Confirmation</a> || 
<a href="<? echo ROOT_URL;?>/store/payment/billing">Billing Info</a> || 
<a href="<? echo ROOT_URL;?>/store/payment/document">Documents</a>

</div>

<link rel="stylesheet" href="<?=ROOT_URL;?>/js/jquery/paging/pagination.css" />
<link rel="stylesheet" href="<?=ROOT_URL;?>/js/calendar/calendar-mos.css" />
<script type="text/javascript" src="<?=ROOT_URL;?>/js/jquery/paging/jquery.pagination.js"></script>
<script type="text/javascript" src="<?=ROOT_URL;?>/js/calendar.js"></script>
<script type="text/javascript" src="<?=ROOT_URL;?>/js/calendar/calendar_mini.js"></script>
<script type="text/javascript" src="<?=ROOT_URL;?>/js/calendar/lang/calendar-en.js"></script>
<script>
	function showResults() {
		 var resultMsg1=0
		 var resultMsg2=0
		 var invdiv ='';
		 <?
		 foreach($this->rowset as $value){
			$arr1[] = $value['orderTotal'];
			$arr2[] = $value['currencyValue'];
			$inv[]  = $value['orderId'].'/'.$value['orderTotal'].'/'.$value['countTotal'];
		 }
		 ?>
		<? 
			for($i=0;$i<count($arr1);$i++){
		?>
		 		if(!document.payconfirm.orderId[<?=$i;?>])
				{
					//alert('only 1');
					if(document.payconfirm.orderId.checked){
						resultMsg1+=parseFloat(<?=($arr1[$i]);?>)
						 resultMsg2+=parseFloat(<?=($arr2[$i]*$arr1[$i]);?>)
						 invdiv+="<?=$inv[$i];?>\n"
					}
				}
				else
				{
			 		if(document.payconfirm.orderId[<?=$i;?>].checked){ 
					 resultMsg1+=parseFloat(<?=($arr1[$i]);?>)
					 resultMsg2+=parseFloat(<?=($arr2[$i]*$arr1[$i]);?>)
					 invdiv+="<?=$inv[$i];?>\n"
					 }
				}
		<?}?>
		 document.getElementById('amountid').innerHTML=resultMsg2		 
		 document.getElementById('amountus').innerHTML=resultMsg1		 
		 document.getElementById('invoicex').innerHTML=invdiv		 
		 //alert(resultMsg1+'*'+resultMsg3+'='+resultMsg2);
	}
</script>
<div class="unit horizontal-center layout">
<div style="padding-top:15px;"></div>
<b><?=$this->numCount;?> data(s) of unconfirmed payment.</b>
<div class="bor"></div>
<div style="padding-top:15px;"></div>
</div>

<form name="payconfirm" id="payconfirm" method="post" action="payconfirm">
<div class="unit horizontal-center layout on-8 columns">
	<div class="fixed column">No&nbsp;</div>
	<div class="fixed column">Invoice&nbsp;</div>
	<div class="fixed column">date Purchased&nbsp;</div>
	<div class="fixed column">Total Price&nbsp;</div>
	<div class="fixed column">Qty&nbsp;</div>
	<div class="fixed column">Method&nbsp;</div>
	<div class="fixed column">Status&nbsp;</div>
	<div class="fixed column">Pay&nbsp;</div>
</div>
<div class="unit horizontal-center layout on-8 columns">
<? $i = $this->offset + 1; ?>
<? if(!empty($_POST['searchid'])):?>
    <?=header('Location: '.$this->url(array('controller'=>'store_payment', 
            'action'=>'detail', 'id'=>$_POST['searchid'])));?>
<? endif; ?>
<? foreach($this->rowset as $value): ?>
<? if($value['orderStatus'] == 3 or $value['orderStatus'] == 5){
	$anchor = 'trdetail';
	}else{
	$anchor = 'detail';
	}
	if($value['orderStatus']==4){
		$color = "green";
	}elseif($value['orderStatus']==6){
		$color = "orange";
	}else{
		$color = "black";
	}
	
?>
	<font color="<?=$color?>">
	<div class="fixed column"><a href="<?=$this->url(array('controller'=>'store_payment', 'action'=>$anchor, 'id'=>$value['orderId'])); ?>"><?=$i;?></a>&nbsp;</div>
	<div class="fixed column"><a href="<?=$this->url(array('controller'=>'store_payment', 
        'action'=>$anchor, 'id'=>$value['orderId'])); ?>"><?=$value['invoiceNumber']; ?></a>&nbsp;</div>
	<div class="fixed column"><?=strftime("%Y-%m-%d", strtotime($value['datePurchased'])); ?>&nbsp;</div>
	<div class="fixed column" align="right"><?=$value['orderTotal']; ?>&nbsp;</div>
	<div class="fixed column" align="center"><?=$value['countTotal']; ?>&nbsp;</div>
	<div class="fixed column"><?=$value['paymentMethod']; ?>&nbsp;</div>
	<div class="fixed column"><?=$value['ordersStatus']; ?>&nbsp;</div>
	<div class="fixed column">
	<? if($value['orderStatus']==4){?>
	<input type="checkbox" id="orderId" name="orderId[<?=$i?>]" disabled="disabled">
	<?php } else {?>
	<input type="checkbox" id="orderId" name="orderId[]" value="<?=$value['orderId']?>" onClick="showResults();">
	<?
	}
	?>
	&nbsp;</div>
	<div style="padding-top:50px;"></div>
	</font>
<? $i++; endforeach;  ?>

</div>
<div class="unit horizontal-center layout">
<table>
	<tr>
		<td>Order ID/Total/Qty</td>
		<td><textarea id="invoicex" name="invoicex" onFocus="blur();">&nbsp;</textarea></td>
	</tr>
	<tr>
		<td>Payment Method</td>
		<td>
        <select name="paymentMethod">
            <option value="atm transfer">ATM Transfer
            <option value="cash bank">Cash Bank
            <option value="transfer">Transfer
            <option value="internet banking">Internet Banking
        </select>
		</td>
	</tr>
	<tr>
		<td>Bank Account Destination</td>
		<td>
	    <select name="destinationAccount">
	        <? foreach($this->bankAccount as $destAccount){
	            $acc = explode("|", $destAccount->settingValue);
	        }
	        foreach($acc as $accN ){
	        ?>
	        <option value="<?=$accN?>"><?=$accN?>
	        <?}?>
	    </select>
		</td>
	</tr>
	<tr>
		<td>Date</td>
		<td><input type="text" name="paymentDate" id="paymentDate" value="<?=date('Y-m-d')?>"><input class="button" type="reset" value="..." onclick="return showCalendar('paymentDate');" name="cmddprebiddate"/></td>
	</tr>
	<tr>
		<td>Amount</td>
		<td>
		<input class="span-1" type="radio" name="currency" value="IDR"><strong>IDR :</strong> <div class="span-1" name="amountid" id="amountid">0</div><hr class="space" />
		<input class="span-1" type="radio" name="currency" checked="checked" value="USD"><strong>USD :</strong> <div class="span-1" name="amountus" id="amountus">0</div>
		</td>
	</tr>
	<tr>
		<td>Sender Account</td>
		<td><input type="text" name="senderAccount"></td>
	</tr>
	<tr>
		<td>Sender Account Name</td>
		<td><input type="text" name="senderAccountName"></td>
	</tr>
	<tr>
		<td>Bank Name</td>
		<td><input type="text" name="bankName"></td>
	</tr>
	<tr>
		<td>Notes</td>
		<td><textarea name="note"></textarea></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td><input type="submit" value="Confirm Payment"/></td>
	</tr>
</table>
</div>
</form>

<table width='100%'>
	<tr>
		<td width=35%>&nbsp;</td>
		<td align=right><div id='catalogPagination' class="pagination">&nbsp;</div></td>
	</tr>
</table>

