<div class="unit horizontal-center layout">
<h2 style="font-weight:bold;">Documents</h2>
<div class="bor"></div>
<div style="padding-top:15px;"></div>
</div>
<div class="unit horizontal-center layout on-2 columns">
	<div class="fixed column" style="width:560px;padding-right:20px;float:left;">
	<a href="<? echo ROOT_URL;?>/site/myaccount">My Account</a> || 
	<a href="<? echo ROOT_URL;?>/store/payment/list">Order </a> || 
	<a href="<? echo ROOT_URL;?>/store/payment/transaction">Transaction </a> || 
	<a href="<? echo ROOT_URL;?>/store/payment/confirm">Confirmation</a> || 
	<a href="<? echo ROOT_URL;?>/store/payment/billing">Billing Info</a> || 
	<a href="<? echo ROOT_URL;?>/store/payment/document">Documents</a>
	
	</div>
	<div class="fixed column" style="width:360px;padding-right:10px;padding-left:5px;float:right;">
	<form id="frmSearch" name="frmSearch" method="POST" >
		<input id="Query" name="Query" size=30 value="<?echo $this->Query;?>"> 
		<input type="hidden" id="Limit" name="Limit" value="10">
		<input type="hidden" id="Offset" name="Offset" value="<?echo $this->Offset;?>">
		<input type="submit" id="btnGoSearch" value="Search">
	</form>
	
	</div>
	<div style="clear:both;"></div>
</div>
<link rel="stylesheet" href="<?=ROOT_URL;?>/js/jquery/paging/pagination.css" />
<script type="text/javascript" src="<?=ROOT_URL;?>/js/jquery/paging/jquery.pagination.js"></script>
<script>
$(document).ready(function(){
	
	var isFirstTime = 1;
	
	// First Parameter: number of items
	// Second Parameter: options object
	var myPageIndex = 0;
	var itemsPerPage = <?=$this->itemsPerPage;?>;
	var currentOffset = <?=$this->offset;?>;
	var limit = <?=$this->limit;?>;
	var currentNode = "<?=$this->currentNode;?>";
	var totalItems = <?=$this->numCount;?>;
	var sort = "<?=$this->sort;?>";
	
	
	var tmpCurrentPageIndex = currentOffset/itemsPerPage;
	
	$("#catalogPagination").pagination(totalItems, 
	{items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPageIndex}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		if(!isFirstTime)
		{
			myPageIndex = new_page_index;
			var nextOffset = (itemsPerPage * myPageIndex);
		
			$("#sOffset").val(nextOffset);
			//$("#frmSearch").submit();
			
			var url = "<?=ROOT_URL;?>/store/payment/document"+currentNode+"/offset/"+nextOffset+"/limit/"+limit+"/Query/<?=$this->Query;?>/sort/"+sort+"/";
			window.location = url;
		}
		isFirstTime = 0;
		return false;
	}
	
	
});
</script>
<div class="unit horizontal-center layout">
<div style="padding-top:15px;"></div>
<b>Data number <?=($this->offset+1>$this->numCount)?$this->numCount:$this->offset+1; ?> to <?=($this->offset+$this->limit>$this->numCount)?$this->numCount:$this->offset+$this->limit>$this->numCount; ?> from <?=$this->numCount;?> data(s)</b>
<div class="bor"></div>
<div style="padding-top:15px;"></div>
</div>
<div class="unit horizontal-center layout on-9 columns">
	<div class="fixed column" align="center">No.</div>
	<div class="fixed column" align="center">Purchasing Date</div>
	<div class="fixed column" align="center">Item Name</div>
	<div class="fixed column" align="center">Download</div>
</div>
<div class="unit horizontal-center layout on-9 columns">
<? $i = $this->offset + 1; ?>
<? foreach($this->rowset as $valueDetail): ?>
	<div class="fixed column" align="right"><?=$i;?></div>
	<div class="fixed column" align="center"><?=strftime("%Y-%m-%d", strtotime($valueDetail['purchasingDate'])); ?>&nbsp;</div>
	<div class="fixed column"><?=$valueDetail['documentName']; ?>&nbsp;</div>
	<div class="fixed column"><a href="<?=KUTU_ROOT_URL;?>/pages/g/<?=$valueDetail['itemId']; ?>" title="click here to download this document">download</a></div>
	<div style="padding-top:50px;"></div>
	
<? $i++; endforeach;  ?>
</div>

<div style="padding-top:15px;"></div>
<table width='100%'>
	<tr>
		<td width=35%>&nbsp;</td>
		<td align=right><div id='catalogPagination' class="pagination">&nbsp;</div></td>
	</tr>
</table>
