<div class="unit horizontal-center layout">
	<h2 style="font-weight:bold;">Notice</h2>
	<div class="bor"></div>
	<h3>We are sorry. You are not registered as POSTPAID Member. Please choose another payment method.</h3>
	<div style="padding-top:15px;"></div>
	<div class="bor"></div>
	<input type="button" onclick="javascript:history.back();" value="Go Back to Previous Page">
	<div class="bor"></div>
</div>