<div class="unit horizontal-center layout">
<h2 style="font-weight:bold;">Search</h2>
<div class="bor"></div>
<div style="padding-top:15px;"></div>
</div>
<div class="unit horizontal-center layout">
	<div class="fixed column">
	<form id="frmSearch" name="frmSearch" method="GET" >
	<input id="Query" name="Query" size=30 value='<?echo $this->Query;?>'>
	<input type="hidden" id="sLimit" name="sLimit" value="10">
	<input type="hidden" id="sOffset" name="sOffset" value="<?echo $this->sOffset;?>">
	<input type="hidden" id="relatedGuid" name="relatedGuid" value="<?echo $this->relatedGuid;?>">
	<input type="submit" id="btnGoSearch" value="Search">
	</form>
	
	</div>
</div>
<link rel="stylesheet" href="<?=ROOT_URL;?>/js/jquery/paging/pagination.css" />
<script type="text/javascript" src="<?=ROOT_URL;?>/js/jquery/paging/jquery.pagination.js"></script>
<script>
$(document).ready(function(){
	
	var isFirstTime = 1;
	
	// First Parameter: number of items
	// Second Parameter: options object
	var myPageIndex = 0;
	var itemsPerPage = <?echo $this->itemsPerPage;?>;
	var currentOffset = <?echo $this->sOffset;?>;
	var limit = <?echo $this->sLimit;?>;
	var currentNode = "<?echo $this->currentNode;?>";
	var totalItems = <?echo $this->numCount;?>;
	var sort = "<?echo $this->sort;?>";
	
	
	var tmpCurrentPageIndex = currentOffset/itemsPerPage;
	
	$("#catalogPagination").pagination(totalItems, 
	{items_per_page:itemsPerPage, callback:handlePaginationClick, current_page:tmpCurrentPageIndex}
	);
	
	function handlePaginationClick(new_page_index, pagination_container) 
	{
		if(!isFirstTime)
		{
			myPageIndex = new_page_index;
			var nextOffset = (itemsPerPage * myPageIndex);
		
			$("#sOffset").val(nextOffset);
			//$("#frmSearch").submit();
			
			var url = "<?echo ROOT_URL;?>/store/payment/search?Query=<?=$this->Query;?>"+currentNode+"&sOffset="+nextOffset+"&sLimit="+limit+"&sort="+sort+"";
			window.location = url;
		}
		isFirstTime = 0;
		return false;
	}
	
	
});
</script>

<?
if($this->numCount == 0){
?>
Hasil pencarian : 0
<?
}else{
?>
Hasil Pencarian : <?=$this->numCount;?>
<hr>

<div class="unit horizontal-center layout on-8 columns">
	<div class="fixed column">No&nbsp;</div>
	<div class="fixed column">Invoice&nbsp;</div>
	<div class="fixed column">date&nbsp;</div>
	<div class="fixed column">Payment Date&nbsp;</div>
	<div class="fixed column">Total Document&nbsp;</div>
	<div class="fixed column">Total Amount&nbsp;</div>
	<div class="fixed column">Method&nbsp;</div>
	<div class="fixed column">Status&nbsp;</div>
</div>
<div class="unit horizontal-center layout on-8 columns">
<? if(!empty($_POST['searchid'])):?>
    <?=header('Location: '.$this->url(array('controller'=>'store_payment', 
            'action'=>'detail', 'id'=>$_POST['searchid'])));?>
<? endif; ?>
<? $i = $this->sOffset + 1; ?>
<? foreach($this->listOrder as $value): ?>
	<div class="fixed column"><a href="<? echo $this->url(array('controller'=>'store_payment', 
        'action'=>'detail', 'id'=>$value['orderId']));?>"><?=$i;?></a>&nbsp;</div>
	<div class="fixed column"><?=$value['invoiceNumber']; ?>&nbsp;</div>
	<div class="fixed column"><?=$value['datePurchased']; ?>&nbsp;</div>
	<div class="fixed column"><?=$value['dateOrderFinished']; ?>&nbsp;</div>
	<div class="fixed column"><?=$value['orderTotal']; ?>&nbsp;</div>
	<div class="fixed column" align="center"><?=$value['countTotal']; ?>&nbsp;</div>
	<div class="fixed column"><?=$value['paymentMethod']; ?>&nbsp;</div>
	<div class="fixed column"><?=$value['ordersStatus']; ?>&nbsp;</div>
	<div style="padding-top:50px;"></div>
	
<? $i++; endforeach;  ?>
</div>


<table width='100%'>
	<tr>
		<td width=35%>&nbsp;</td>
		<td align=right><div id='catalogPagination' class="pagination"></div></td>
	</tr>
</table>
<?
}
?>