<div class="unit horizontal-center layout">
	<h2 style="font-weight:bold;">Payment Successful</h2>
	<div class="bor"></div>
	<h3>Thank you for your order.</h3>
	Your payment has been succesfully recorded to our database, now you can continue to <a href="<?=ROOT_URL?>/store/payment/document">download the document(s)</a> or just continue <a href="<?=ROOT_URL?>/pusatdata">browsing our database</a>.
	<div style="padding-top:15px;"></div>
	<div class="bor"></div>
</div>
