<div class="unit">
	<div class="container" style="padding:0 0px 0 20px;background:">
		<script src="http://widgets.twimg.com/j/2/widget.js"></script>
		<script>
		new TWTR.Widget({
			version: 2,
			type: 'profile',
			rpp: 5,
			interval: 6000,
			width: 250,
			height: 300,
			theme: {
				shell: {
			    	background: '#8ec1da',
			    	color: '#ffffff'
			  	},
				tweets: {
					background: '#ffffff',
					color: '#444444',
					links: '#1985b5'
			    }
			},
			features: {
			    scrollbar: false,
			    loop: false,
			    live: false,
			    hashtags: true,
			    timestamp: true,
			    avatars: false,
			    behavior: 'all'
			}
		}).render().setUser('hukumonline').start();
		</script>
	</div>
</div>