<script type="text/javascript">
	$(document).ready(function(){
		
		var message = "<?echo $this->message;?>";
		if(message!="")
		{
			alert (message);
		}
		
		$("#frmNewFolder").validate();
		
	});
</script>
<div class="span-24 last">
<h2 class="alt">Folder Management: Add New Folder into <?php echo $this->nodeTitle;?></h2>
<hr class="space">
<form class="" id="frmNewFolder" method="post" action="">
	<fieldset>
		<legend>Folder Info</legend>
		<p>
			<label for="title">Folder Title</label>
			<input type="hidden" id="node" name="node" value="<?php echo $this->node;?>">
			<input id="title" name="title" class="required" size="50" value="<?php echo $this->row->title;?>" />
		</p>
		<p>
			<label for="description">Description</label>
			<textarea id="description" name="description" class="" cols=35 rows="1"><?php echo $this->row->description;?></textarea>
		</p>
		<p>
			<label for="viewOrder">Menu View Order</label>
			<input id="viewOrder" name="viewOrder" class="" size="10" value="<?php echo $this->row->viewOrder;?>" />
		</p>
		<p>
			<label for="cmsParams">Cms Parameters</label>
			<input id="cmsParams" name="cmsParams" class="" size="50" value="<?php echo $this->row->cmsParams;?>" />
		</p>
		<p>
			<input class="submit" type="submit" value="Save"/>
		</p>
	</fieldset>
</form>
</div>