<div class="unit">
	<div class="container">
	<!-- zone topA1 -->
	<?php if ($this->isBannerExist('6247')) { ?>
	<div class="unit horizontal-center layout on-2 columns">
		<div class="fixed column" style="width:647px;"><?=$this->action('view','banner','hol-site',array('zid'=>'6247')); ?></div>
		<div class="fixed column" style="width:310px;height:90px;"><?=$this->action('view','banner','hol-site',array('zid'=>'2046')); ?></div>
	</div>
	<div style="padding-top:5px;"></div>
	<?php 
	} 
	// zone topA2 
	else if ($this->isBannerExist('2046'))
	{
	?>
	<div class="unit horizontal-center layout on-2 columns">
		<div class="fixed column" style="width:647px;"><?=$this->action('view','banner','hol-site',array('zid'=>'6247')); ?></div>
		<div class="fixed column" style="width:310px;height:90px;"><?=$this->action('view','banner','hol-site',array('zid'=>'2046')); ?></div>
	</div>
	<div style="padding-top:5px;"></div>
	<?php 
	} 
	// zone topA3 
	else if ($this->isBannerExist('6641'))
	{
	?>
	<div class="unit horizontal-center layout">
	<?php 
		echo $this->action('view','banner','hol-site',array('zid'=>'6641'));
	?>
	</div>
	<div style="padding-top:5px;"></div>
	<?php 
	}
	?>
	<div class="unit horizontal-center layout on-2 columns">
		<div class="fixed column" style="width:640px;padding-right:20px;">
			<?php echo $this->action('detail-290910','widgets_catalog','hol-site',array('guid'=>$this->catalogGuid,'page'=>$this->page)); ?>
		</div>
		<div class="fixed column" style="width:300px;">
			<?php echo $this->action('kanan','widgets_sidebar','hol-site'); ?>
		</div>
	</div>
 	</div>
</div>