<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>hukumonline.com print PDF</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/resources/images/hole_small.ico" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/resources/css/printpdf.css" type="text/css" media="screen, projection">
</head>
<body>
	<?=$this->layout()->content; ?>
</body>
</html>