<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>hukumonline.com: <?=$this->identity;?></title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" href="<?=$this->baseUrl();?>/resources/images/hole_small.ico" />
	<script type="text/javascript" src="<?=$this->baseUrl(); ?>/js/jquery/jquery-1.2.3.pack.js"></script>
	<link rel="stylesheet" type="text/css" media="all" href="<?=$this->baseUrl();?>/resources/css/elastic.css" />
	<script src="<?=$this->baseUrl();?>/resources/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
	<link rel="stylesheet" type="text/css" media="screen" href="<?=$this->baseUrl();?>/resources/css/typography.css" />
	<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl(); ?>/resources/css/calender.css" />
	<script src="<?=$this->baseUrl();?>/js/jquery/newsticker/jquery.newsticker.pack.js" type="text/javascript"></script>
	<script src="<?=$this->baseUrl(); ?>/js/globe.js" type="text/javascript"></script>
</head>
<body>
	<?=$this->render("header.phtml"); ?>
	<div style="padding-top: 5px"></div>
	<?=$this->layout()->content?>
	<?=$this->render("footer.phtml"); ?>
	<script type="text/javascript">
	
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	
	</script>
	
	<script type="text/javascript">
	
	try{
	
	var pageTracker = _gat._getTracker("UA-2695772-1");
	
	pageTracker._trackPageview();
	
	} catch(err) {}
	
	</script>	
</body>
</html>