<div class="unit footer-container">
		<div class="unit">
			<div class="container" style="background:#3a3a3a;color:white;padding-right:30px;padding-left:30px;padding-top:15px;padding-bottom:5px;">
				<div class="columns on-4">	
					<div class="column">
						<div class="container"><img src="<?=$this->getRootUrl(); ?>/resources/images/tfooter_talks.jpg" width="104" border="0" height="46" hspace="0"  align="left" /></div>
						<div class="container">
						<?=$this->action('talk','widgets_content','hol-site');?>
						</div>
					</div>
					<div class="column">
						<div class="container"><img src="<?=$this->getRootUrl(); ?>/resources/images/tfooter_agenda.jpg" vspace="0" width="117" border="0" height="46" hspace="0"  align="left"/></div>
						<div id="showDiv1" class="container" style="width:100%;padding-top:10px;text-align:center;">
						<?=$this->action('browse','manager','agenda');?>
						</div>
					</div>
					<div class="column">
						<div class="container"><img src="<?=$this->getRootUrl(); ?>/resources/images/tfooter_komunitas.jpg" vspace="0" width="148" border="0" height="46" hspace="0"  align="left"/></div>
						<div class="container">
						<?=$this->action('komunitas','widgets_content','hol-site');?>
						</div>
					</div>
					<div class="column">
						<div class="container"><img src="<?=$this->getRootUrl(); ?>/resources/images/tfooter_suarapembaca.jpg" vspace="0" width="177" border="0" height="46" hspace="0"  align="left"/></div>
						<div class="container">
						<?=$this->action('suarapembaca','widgets_content','hol-site');?>
						</div>
					</div>
				</div>
			</div>
			<div class="container" style="background:#DDDDDD;color:black;padding-right:30px;padding-left:30px;padding-top:15px;padding-bottom:2px;">
				<div class="footnote-down">
				<a href="<?=$this->getRootUrl(); ?>" class="footnote">Home</a> |  <a href="<?=$this->getRootUrl(); ?>/tentangkami" class="footnote">Tentang Kami</a>  |   <a href="<?=$this->getRootUrl(); ?>/kodeetik" class="footnote">Kode Etik</a> | <a href="<?=$this->getRootUrl(); ?>/mitrakami" class="footnote">Mitra Kami</a> | <a href="<?=$this->getRootUrl(); ?>/syaratketentuan" class="footnote">Syarat dan Ketentuan</a> <br />
				 Informasi yang tersedia di<a href="<?=$this->getRootUrl(); ?>" class="footnote"> www.hukumonline.com</a> tidak ditujukan sebagai suatu nasehat hukum,<br />
				 namun hanya memberikan gambaran umum terhadap suatu informasi atau permasalahan hukum yang sedang dihadapi.<br />
				 Akses dan penggunaan situs ini tunduk pada Syarat dan Ketentuan &copy; 2009
				 </div>
			</div>
		</div>
</div>