<!-- zone A1 -->
<div class="unit horizontal-center layout on-2 columns">
	<div class="fixed column" style="width:647px;">

<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=16");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a8fca4cd&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=16&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a8fca4cd' border='0' alt='' /></a></noscript>

	
	</div>
	<div class="fixed column" style="width:310px;">

<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=3");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=ac33719a&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=3&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=ac33719a' border='0' alt='' /></a></noscript>

	
	</div>
</div>



<div class="unit horizontal-center layout on-2 columns" style="padding-top:5px;">
<div class="fixed column" style="width:310px">
	<?=$this->action('utama','widgets_content','hol-site');?>
	<div class="bersih"></div>
	<div style="padding-top:5px;"></div>
	<!-- zone B1 -->
	
<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=4");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a2d7bdab&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=4&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a2d7bdab' border='0' alt='' /></a></noscript>
	
	<div style="padding-top:5px;"></div>
	<?=$this->action('fokus','widgets_content','hol-site');?>
</div>
<div class="fixed column" style="width:650px;">
	<div class="container">
		<div class="unit on-2 columns">
			<div class="fixed column" style="width:330px;padding-left:5px;">
			<?=$this->action('terbaru','widgets_content','hol-site');?>
			<div class="bersih"></div>
			<div style="padding-top:5px;"></div>
			<?=$this->action('isuhangat','widgets_content','hol-site');?>
			</div>
			<div class="fixed column" style="width:308px;padding-left:5px;">
			<?=$this->action('klinik','widgets_content','hol-site');?>
			<div class="bersih"></div>
			<div style="padding-top:2px;">&nbsp;</div>
			<!-- zone middleB -->
			<?=$this->action('view','banner','hol-site',array('zid'=>'4304')); ?>
			<!-- AdJuggler 7 request
			Type: Single Ad
			Ad Placement: News/300x250
			Channel: News
			Ad Size: IMU (Medium Rec Pop-Up,300X250)
			Position: 0
			-->
			<script type="text/javascript" language="JavaScript">
			  aj_server = 'http://adj.adstars.co.id/servlet/ajrotator/'; aj_tagver = '1.0';
			  aj_zone = 'adstars'; aj_adspot = '130529'; aj_page = '0'; aj_dim ='78535'; aj_ch = '123589'; aj_ct = ''; aj_kw = '';
			  aj_pv = true; aj_click = '';
			</script><script type="text/javascript" language="JavaScript" src="http://cdn.hadj7.adjuggler.net/banners/Client84267/1308210017899_ajtg.js"></script>
			
			</div>
		</div>
	</div>
</div>
</div>
<!-- zone C1-C2-C3 -->

<div class="unit horizontal-center layout on-3 columns" style="padding-top:5px;">
	<div class="fixed column" style="width:320px;">

<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=6");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a52ab127&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=6&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a52ab127' border='0' alt='' /></a></noscript>

	
	</div>
	<div class="fixed column" style="width:320px;">
	
<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=7");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a367f365&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=7&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a367f365' border='0' alt='' /></a></noscript>
	
	
	</div>
	<div class="fixed column" style="width:320px;">
	
<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=8");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a51839a2&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=8&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a51839a2' border='0' alt='' /></a></noscript>
	
	
	</div>
</div>


<div class="unit horizontal-center layout">
	<div class="pembatas">
		<img src="resources/images/line_yellow.jpg" width="10" height="14" />
	</div>
</div>
<div class="unit horizontal-center layout on-2 columns">
<div class="fixed column" style="width:278px;">
	<div class="td_peraturan1">
		<div class="judulnaik">
			<h1>Pusat Data hukumonline</h1>
		</div>
		<div class=c-isi>
			<p>Hukumonline Legal Directory (HOLD) Online memuat koleksi data hukum elektronik terlengkap di Indonesia.</p>
			<div style="padding-top:15px;"></div>
			<a href="javascript:;" class="peraturan">Selengkapnya</a>
			<div class="pdh">
				<ul id="listnoline">
					<li><img src="resources/images/arrow02.jpg" width="9" height="9" /><a href="<?=$this->getRootUrl(); ?>/pusatdata" class="peraturan"> Browse</a></li>
					<li><img src="resources/images/arrow02.jpg" width="9" height="9" /><a href="<?=$this->getRootUrl(); ?>/pusatdata/advanced_search" class="peraturan"> Advance Search</a></li>
					<li><a href="http://id.hukumonline.com/identity/daftar" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('signup','','resources/images/signupnow_f2.jpg',1)"><img src="resources/images/signupnow.jpg" alt="Sign up Now !" name="signup" width="217" height="89" border="0" id="signup" /></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<div class="fixed column" style="width:650px;">
	<div class="container">
		<div class="unit on-2 columns">
			<div class="fixed column" style="width:365px;padding-left:5px;">
				<div class="td_peraturan3">
					<div id="lilmenu">
						<div class="mati" title="peraturanterbaru"><span>Dokumen Terbaru</span></div>
						<div class="hidup" title="peraturanpilihan"><span>Pilihan</span></div>
					</div>
					<div id="peraturanterbaru" class="tutup">
					<?=$this->ajaxActionRenderer(ROOT_URL.'/peraturan');?>
					</div>
			        <div id="peraturanpilihan" class="buka">
			        <?=$this->action('peraturanpilihan','widgets_content','hol-site'); ?>
			       	</div>
		       	</div>
			</div>
			<div class="fixed column" style="width:268px;padding-left:5px;">
<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=17");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a885a305&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=17&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a885a305' border='0' alt='' /></a></noscript>
			
			</div>
		</div>
	</div>
</div>
</div>
<!-- zone D1 -->
<div class="unit horizontal-center layout" style="padding-top:5px;">
<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=13");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a289743e&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=13&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a289743e' border='0' alt='' /></a></noscript>

</div>
<div class="unit horizontal-center layout">
	<div class="pembatas"><img src="resources/images/line_yellow.jpg" height="14" /></div>
</div>
<div class="unit horizontal-center layout on-2 columns">
<div class="fixed column" style="width:460px;">
	<?=$this->action('kolom','widgets_content','hol-site');?>
</div>
<div class="fixed column" style="width:500px;">
	<div class="container">
		<div class="unit on-2 columns">
			<div class="fixed column" style="width:250px;padding-left:5px;">
			<?=$this->action('tokoh','widgets_content','hol-site');?>
			</div>
			<div class="fixed column" style="width:240px;padding-left:5px;">
			<?=$this->action('resensi','widgets_content','hol-site');?>
			</div>
		</div>
	</div>
</div>
</div>
<div class="bersih"></div>
<div class="unit horizontal-center layout on-4 columns">
<div class="fixed column" style="width:235px;padding-top:5px;">
	<?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb9','title'=>'Info'));?>
</div>
<div class="fixed column" style="width:235px;padding-top:5px;padding-left:5px;">
	<?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb14','title'=>'Jeda'));?>
</div>
<div class="fixed column" style="width:235px;padding-top:5px;padding-left:5px;">
	<?=$this->action('ijt','widgets_content','hol-site',array('folderGuid'=>'fb18','title'=>'Tajuk'));?>
</div>
<div class="fixed column" style="width:240px;padding-top:5px;padding-left:5px;">
	<?=$this->action('view','manager','polling');?>
</div>
</div>
<!-- zone D2 -->
<div class="unit horizontal-center layout" style="padding-top:5px;">
<!--/* OpenX Javascript Tag v2.8.5 */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://openx.hukumonline.com/www/delivery/...'
  * to
  *   'https://openx.hukumonline.com/www/delivery/...'
  *
  * This noscript section of this tag only shows image banners. There
  * is no width or height in these banners, so if you want these tags to
  * allocate space for the ad before it shows, you will need to add this
  * information to the <img> tag.
  *
  * If you do not want to deal with the intricities of the noscript
  * section, delete the tag (from <noscript>... to </noscript>). On
  * average, the noscript tag is called from less than 1% of internet
  * users.
  */-->

<script type='text/javascript'><!--//<![CDATA[
   var m3_u = (location.protocol=='https:'?'https://openx.hukumonline.com/www/delivery/ajs.php':'http://openx.hukumonline.com/www/delivery/ajs.php');
   var m3_r = Math.floor(Math.random()*99999999999);
   if (!document.MAX_used) document.MAX_used = ',';
   document.write ("<scr"+"ipt type='text/javascript' src='"+m3_u);
   document.write ("?zoneid=14");
   document.write ('&amp;cb=' + m3_r);
   if (document.MAX_used != ',') document.write ("&amp;exclude=" + document.MAX_used);
   document.write (document.charset ? '&amp;charset='+document.charset : (document.characterSet ? '&amp;charset='+document.characterSet : ''));
   document.write ("&amp;loc=" + escape(window.location));
   if (document.referrer) document.write ("&amp;referer=" + escape(document.referrer));
   if (document.context) document.write ("&context=" + escape(document.context));
   if (document.mmm_fo) document.write ("&amp;mmm_fo=1");
   document.write ("'><\/scr"+"ipt>");
//]]>--></script><noscript><a href='http://openx.hukumonline.com/www/delivery/ck.php?n=a79735d3&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.hukumonline.com/www/delivery/avw.php?zoneid=14&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a79735d3' border='0' alt='' /></a></noscript>

</div>