<?php 
/*
try 
{
	if($this->isAllowed('all-access', 'all','content')) {
*/ 
?>
<div style="width:auto;">
    <div class="x-box-tl"><div class="x-box-tr"><div class="x-box-tc"></div></div></div>
    <div class="x-box-ml"><div class="x-box-mr"><div class="x-box-mc">
    	<h3 style="margin-bottom:5px;"><img border="0" height="14" width="14" src="./js/extjs/resources/images/default/silk/icons/folder_add.png">&nbsp;Create a new directory/file ...</h3>
        <div id="AddDirForm"></div>
        <div class="ext_statusbar" id="statusBar"></div>
    </div></div></div>
    <div class="x-box-bl"><div class="x-box-br"><div class="x-box-bc"></div></div></div>
</div>

<script type="text/javascript">
	typeOfFolder = new Ext.data.SimpleStore({
		id:'tof',
		fields: ['type','content'],
		data:[['cms','Berita'],['dms','Peraturan'],['eventcalendar','Project'],['klinik','Klinik'],['marketing','Marketing'],['membership','Membership'],['menu','Menu']]
	});
	var sform = new Ext.FormPanel({
		labelWidth: 125,
		url: './admin/dms_foldermanager/save',
		frame: false,
		bodyStyle: 'border:none;background: none;',
		defaultType: 'textfield',
		
		items:[{
			fieldLabel: 'Name',
			name: 'title',
			id: 'title',
			width: 175,
			allowBlank: false
		},
		{
			fieldLabel: 'Menu View Order',
			name: 'viewOrder',
			id: 'viewOrder',
			width: 125
		},
		{
			fieldLabel: 'Cms Parameters',
			name: 'cmsParams',
			id: 'cmsParams',
			width: 300
		},
		{
			fieldLabel: 'Description',
			name: 'description',
			id: 'description',
			width: 175
		},
			new Ext.form.ComboBox({
				fieldLabel:'Type of Folder',
				mode: 'local',
				typeAhead: false,
				triggerAction:"all",
				lazyRender: true,
				store:typeOfFolder,
				valueField: 'type',
				displayField: 'content'
			})
		],
		
		buttons: [{
			text: 'Save',
			handler: function() {
				sform.form.submit({
					reset: true,
					waitMsg: 'Saving directory/file name ...',
					success: function(form, action)	{
						parentDir = tree.getSelectionModel().getSelectedNode();
						parentDir.reload();
						parentDir.select();
						dialog.destroy();
						dialog.hide();
					},
					failure: function(form, action) {
						
					},
					scope: sform,
					params: 
					{
						parentGuid: '<?=$this->parentGuid; ?>'
					}
				})
			}
		},{
			text: 'Cancel',
			handler: function() {
				dialog.destroy();
				dialog.hide();
			}
		}
		]
	});
	
	sform.render('AddDirForm');
	
	Ext.get('title').focus();
	
</script>
<?php //} else { echo $this->action('restricted','error','admin',array('type'=>'user','num'=>101)); ?>
<?php 
/*
}
} catch (Exception $e)
{
	echo $e->getMessage();
}
*/
?>